<?php

return [
    [
        'id'                    => 1,
        'cod'                   => 'b7ecc8af-25c1-4981-a891-cc60c3464f6c',
        'empresa'               => 1,
        'titulo'                => 'Markt Club',
        'link_site'             => 'clube.marktclub.com.br',
        'logo'                  => 'logo_marktclub_tem_mais.png',
        'cor'                   => '#FF6F00',
        'contato_telefone'      => '6132023003',
        'contato_whatsapp'      => '61912345678',
        'contato_email'         => 'atendimento@markt.club',
        'menu_primeiro_acesso'  => 1,
        'menu_faq'              => 1,
        'menu_acesso_rapido'    => 1,
        'menu_como_funciona'    => 1,
        'menu_convenio'         => 1,
        'menu_convenio_mapa'    => 1,
        'menu_cinema'           => 1,
        'menu_turismo_clube'    => 1,
        'menu_historico'        => 1,
        'menu_sicoob_credito'   => 1,
        'menu_medicamento'      => 1,
        'menu_automovel'        => 1,
        'menu_saude_vitoria'    => 1,
        'menu_saude_amil'       => 1,
        'menu_saude_seguros'    => 1,
        'menu_cashback'         => 1,
        'menu_indicacao'        => 1,
        'menu_cupom'            => 1,
        'menu_odontologia'      => 1,
        'menu_premium'          => 1,
        'menu_dependente'       => 1,
        'menu_carteiria'        => 1,
        'menu_salavip'          => 1,
        'menu_sair'             => 1,
        'status'                => 1
    ],
    [
        'id'                    => 31,
        'cod'                   => '236e76ea7af7e44d92294b31bb029a9b',
        'empresa'               => 2,
        'titulo'                => 'Anafe Card',
        'link_site'             => 'anafecard.com.br',
        'logo'                  => '70ff785234195b33e0036ca434feaa3c.png',
        'cor'                   => '#004E7D',
        'menu_primeiro_acesso'  => 1,
        'menu_faq'              => 1,
        'menu_acesso_rapido'    => 1,
        'menu_como_funciona'    => 1,
        'menu_convenio'         => 1,
        'menu_convenio_mapa'    => 1,
        'menu_cinema'           => 1,
        'menu_turismo_clube'    => 1,
        'menu_historico'        => 1,
        'menu_sicoob_credito'   => 1,
        'menu_medicamento'      => 1,
        'menu_automovel'        => 1,
        'menu_saude_vitoria'    => 1,
        'menu_saude_amil'       => 1,
        'menu_saude_seguros'    => 1,
        'menu_cashback'         => 1,
        'menu_indicacao'        => 1,
        'menu_cupom'            => 1,
        'menu_odontologia'      => 1,
        'menu_premium'          => 1,
        'menu_dependente'       => 1,
        'menu_carteiria'        => 1,
        'menu_salavip'          => 1,
        'menu_sair'             => 1,
        'status'                => 1
    ],
    [
        'id'        => 134,
        'cod'       => '14bd832c9740b2e3093d402fd58c2f93',
        'empresa'   => 153,
        'titulo'    => 'Fenae',
        'link_site' => 'convenios.fenae.org.br',
        'logo'      => 'a96542ac6f8df4c7acbc53d1aa29de3d.png',
        'cor'       => '#20409a',
        'status'    => 1
    ],
    [
        'id'        => 165,
        'cod'       => '5cc28dab736cb7d4ef436ee2447a07ee',
        'empresa'   => 198,
        'titulo'    => 'CVS MAIS',
        'link_site' => 'clube.cvsmais.com.br',
        'logo'      => 'logo_cvsmais_tem_mais.png',
        'cor'       => '#f00068',
        'status'    => 1
    ],
    [
        'id'        => 221,
        'cod'       => '122f833e84a78931e6fdcfa2e2a58771',
        'empresa'   => 1967,
        'titulo'    => 'Clube D+',
        'link_site' => 'clubedmais.com.br',
        'logo'      => 'logo_cvsmais_tem_mais.png',
        'cor'       => '#d9031c',
        'status'    => 1
    ],
    [
        'id'        => 72,
        'cod'       => '61df17919405cf68f723510ec3af4acd',
        'empresa'   => 82,
        'titulo'    => 'CLUBE DE VANTAGENS SINPOLDF',
        'link_site' => 'sinpoldf.temmaisvantagens.com.br',
        'logo'      => '27e13bb65402e5c25978b225c9775814.png',
        'cor'       => '#f00068',
        'status'    => 1
    ]
];
