<?php

return [
    [
        'id'                        => 1,
        'uuid'                      => 'b7ecc8af-25c1-4981-a891-cc60c3464f6c',
        'id_admin_empresa'          => 1,
        'titulo'                    => 'Markt Club',
        'link_clube'                => 'clube.marktclub.com.br',
        'logo_principal'            => '936c2cff-9944-4818-82ac-d7313193c08c',
        'logo_secundaria'           => '2a2210de-ea43-449a-9d3f-158c24ec3eac',
        'favicon'                   => '2d388efe-bc69-4bd0-bcbb-01084e41b9ad',
        'cor_principal'             => '#FF6F00',
        'cor_secundaria'            => '#FF6F00',
        'contato_telefone'          => '6132023003',
        'contato_whatsapp'          => '61912345678',
        'contato_email'             => 'atendimento@markt.club',
        'contato_endereco'          => 'SIG Quadra 4 Lote 125/175 Bloco A Sala 10, Brasília/DF',
        'contato_horario'           => '9h às 18h de Seg. a Sex.',
        'menu_primeiro_acesso'      => 1,
        'menu_faq'                  => 1,
        'menu_acesso_rapido'        => 1,
        'menu_como_funciona'        => 1,
        'menu_loja'                 => 1,
        'menu_mapa'                 => 1,
        'menu_cinema'               => 1,
        'menu_turismo'              => null,
        'menu_historico'            => 1,
        'menu_credito_sicoob'       => 1,
        'menu_farmacia'             => 1,
        'menu_automovel'            => 1,
        'menu_saude_vitoria'        => 1,
        'menu_saude_amil'           => 1,
        'menu_saude_seguro'         => 1,
        'menu_tema'                 => 1,
        'menu_corrida'              => 1,
        'menu_show_nacional'        => 1,
        'menu_show_internacional'   => 1,
        'menu_saude_cnu'            => 1,
        'menu_saude_florianopolis'  => 1,
        'menu_cashback'             => 1,
        'menu_indicar_usuario'      => 1,
        'menu_indicar_loja'         => 1,
        'menu_cupom'                => 1,
        'menu_odontologico'         => 1,
        'menu_premium'              => 1,
        'menu_dependente'           => 1,
        'menu_carteira'             => 1,
        'menu_salavip'              => 1,
        'menu_samsung'              => 1,
        'menu_corrida'              => 1,
        'menu_show_nacional'        => 1,
        'menu_show_internacional'   => 1,
        'menu_sair'                 => 1,
        'administrado_status'       => 1,
        'chat_status'               => 1,
        'menu_meu_parceiro'         => 1,
        'tipo_ativacao'             => 1,
        'status'                    => 1
    ],
    [
        'id'                        => 31,
        'uuid'                      => '236e76ea7af7e44d92294b31bb029a9b',
        'id_admin_empresa'          => 2,
        'titulo'                    => 'Anafe Card',
        'link_clube'                => 'anafecard.com.br',
        'cor_principal'             => '#004E7D',
        'menu_primeiro_acesso'      => 1,
        'menu_faq'                  => 1,
        'menu_acesso_rapido'        => 1,
        'menu_como_funciona'        => 1,
        'menu_loja'                 => 1,
        'menu_mapa'                 => 1,
        'menu_cinema'               => 1,
        'menu_turismo'              => null,
        'menu_historico'            => 1,
        'menu_credito_sicoob'       => 1,
        'menu_farmacia'             => 1,
        'menu_automovel'            => 1,
        'menu_saude_vitoria'        => 1,
        'menu_saude_amil'           => 1,
        'menu_saude_seguro'         => 1,
        'menu_saude_cnu'            => 1,
        'menu_saude_florianopolis'  => 1,
        'menu_cashback'             => 1,
        'menu_indicar_usuario'      => 1,
        'menu_indicar_loja'         => 1,
        'menu_meu_parceiro'         => 1,
        'menu_cupom'                => 1,
        'menu_odontologico'         => 1,
        'menu_premium'              => 1,
        'menu_dependente'           => 1,
        'menu_corrida'              => 1,
        'menu_show_nacional'        => 1,
        'menu_show_internacional'   => 1,
        'menu_carteira'             => 1,
        'menu_salavip'              => 1,
        'menu_sair'                 => 1,
        'status'                    => 1
    ],
    [
        'id'               => 134,
        'uuid'             => '14bd832c9740b2e3093d402fd58c2f93',
        'id_admin_empresa' => 153,
        'titulo'           => 'Fenae',
        'link_clube'       => 'convenios.fenae.org.br',
        'cor_principal'    => '#20409a',
        'status'           => 1
    ],
    [
        'id'               => 165,
        'uuid'             => '5cc28dab736cb7d4ef436ee2447a07ee',
        'id_admin_empresa' => 198,
        'titulo'           => 'CVS MAIS',
        'link_clube'       => 'clube.cvsmais.com.br',
        'cor_principal'    => '#f00068',
        'status'           => 1
    ],
    [
        'id'               => 221,
        'uuid'             => '122f833e84a78931e6fdcfa2e2a58771',
        'id_admin_empresa' => 1967,
        'titulo'           => 'Clube D+',
        'link_clube'       => 'clubedmais.com.br',
        'cor_principal'    => '#d9031c',
        'status'           => 1
    ],
    [
        'id'               => 72,
        'uuid'             => '61df17919405cf68f723510ec3af4acd',
        'id_admin_empresa' => 82,
        'titulo'           => 'CLUBE DE VANTAGENS SINPOLDF',
        'link_clube'       => 'sinpoldf.temmaisvantagens.com.br',
        'cor_principal'    => '#f00068',
        'status'           => 1
    ]
];
