<?php

return [
    [
        'id'                        => 1,
        'uuid'                      => 'b7ecc8af-25c1-4981-a891-cc60c3464f6c',
        'id_admin_empresa'          => 1,
        'titulo'                    => 'Markt Club',
        'link_clube'                => 'clube.marktclub.com.br',
        'logo'                      => 'logo_marktclub_tem_mais.png',
        'cor'                       => '#FF6F00',
        'contato_telefone'          => '6132023003',
        'contato_whatsapp'          => '61912345678',
        'contato_email'             => 'atendimento@markt.club',
        'menu_primeiro_acesso'      => 1,
        'menu_faq'                  => 1,
        'menu_acesso_rapido'        => 1,
        'menu_como_funciona'        => 1,
        'menu_loja'                 => 1,
        'menu_mapa'                 => 1,
        'menu_cinema'               => 1,
        'menu_turismo'              => null,
        'menu_historico'            => 1,
        'menu_credito_sicoob'       => 1,
        'menu_farmacia'             => 1,
        'menu_automovel'            => 1,
        'menu_saude_vitoria'        => 1,
        'menu_saude_amil'           => 1,
        'menu_saude_seguro'         => 1,
        'menu_saude_cnu'            => 1,
        'menu_saude_florianopolis'  => 1,
        'menu_cashback'             => 1,
        'menu_indicar_usuario'      => 1,
        'menu_indicar_loja'         => 1,
        'menu_cupom'                => 1,
        'menu_odontologico'         => 1,
        'menu_premium'              => 1,
        'menu_dependente'           => 1,
        'menu_carteira'             => 1,
        'menu_salavip'              => 1,
        'menu_corrida'              => 1,
        'menu_show_nacional'        => 1,
        'menu_show_internacional'   => 1,
        'menu_sair'                 => 1,
        'administrado_status'       => 1,
        'chat_status'               => 1,
        'menu_meu_parceiro'         => 1,
        'tipo_ativacao'             => 1,
        'status'                    => 1
    ],
    [
        'id'                        => 31,
        'uuid'                      => '236e76ea7af7e44d92294b31bb029a9b',
        'id_admin_empresa'          => 2,
        'titulo'                    => 'Anafe Card',
        'link_clube'                => 'anafecard.com.br',
        'logo'                      => '70ff785234195b33e0036ca434feaa3c.png',
        'cor'                       => '#004E7D',
        'menu_primeiro_acesso'      => 1,
        'menu_faq'                  => 1,
        'menu_acesso_rapido'        => 1,
        'menu_como_funciona'        => 1,
        'menu_loja'                 => 1,
        'menu_mapa'                 => 1,
        'menu_cinema'               => 1,
        'menu_turismo'              => null,
        'menu_historico'            => 1,
        'menu_credito_sicoob'       => 1,
        'menu_farmacia'             => 1,
        'menu_automovel'            => 1,
        'menu_saude_vitoria'        => 1,
        'menu_saude_amil'           => 1,
        'menu_saude_seguro'         => 1,
        'menu_saude_cnu'            => 1,
        'menu_saude_florianopolis'  => 1,
        'menu_cashback'             => 1,
        'menu_indicar_usuario'      => 1,
        'menu_indicar_loja'         => 1,
        'menu_meu_parceiro'         => 1,
        'menu_cupom'                => 1,
        'menu_odontologico'         => 1,
        'menu_premium'              => 1,
        'menu_dependente'           => 1,
        'menu_corrida'              => 1,
        'menu_show_nacional'        => 1,
        'menu_show_internacional'   => 1,
        'menu_carteira'             => 1,
        'menu_salavip'              => 1,
        'menu_sair'                 => 1,
        'status'                    => 1
    ],
    [
        'id'               => 134,
        'uuid'             => '14bd832c9740b2e3093d402fd58c2f93',
        'id_admin_empresa' => 153,
        'titulo'           => 'Fenae',
        'link_clube'       => 'convenios.fenae.org.br',
        'logo'             => 'a96542ac6f8df4c7acbc53d1aa29de3d.png',
        'cor'              => '#20409a',
        'status'           => 1
    ],
    [
        'id'               => 165,
        'uuid'             => '5cc28dab736cb7d4ef436ee2447a07ee',
        'id_admin_empresa' => 198,
        'titulo'           => 'CVS MAIS',
        'link_clube'       => 'clube.cvsmais.com.br',
        'logo'             => 'logo_cvsmais_tem_mais.png',
        'cor'              => '#f00068',
        'status'           => 1
    ],
    [
        'id'               => 221,
        'uuid'             => '122f833e84a78931e6fdcfa2e2a58771',
        'id_admin_empresa' => 1967,
        'titulo'           => 'Clube D+',
        'link_clube'       => 'clubedmais.com.br',
        'logo'             => 'logo_cvsmais_tem_mais.png',
        'cor'              => '#d9031c',
        'status'           => 1
    ],
    [
        'id'               => 72,
        'uuid'             => '61df17919405cf68f723510ec3af4acd',
        'id_admin_empresa' => 82,
        'titulo'           => 'CLUBE DE VANTAGENS SINPOLDF',
        'link_clube'       => 'sinpoldf.temmaisvantagens.com.br',
        'logo'             => '27e13bb65402e5c25978b225c9775814.png',
        'cor'              => '#f00068',
        'status'           => 1
    ]
];
