version: '3'
services:
    nginx:
        image: andrerodrigue5/nginx-php8.3
        container_name: web-{{nome}}
        ports:
            - "{{portaHttp}}:80"
            - "{{portaHttps}}:443"
        volumes:
            - .:/var/www/html/
            - ./files/docker_host:/etc/nginx/sites-enabled/
        networks:
            - docker-rede
        depends_on:
            - "mysql"
        restart: always
    mysql:
        image: mysql:8.2.0
        container_name: db-{{nome}}
        ports:
            - "{{portaDb}}:3306"
        environment:
            MYSQL_DATABASE: {{dbNome}}
            MYSQL_ROOT_PASSWORD: {{dbSenha}}
        networks:
            - docker-rede
        volumes:
            - ./files/banco/mysql/:/var/lib/mysql
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma-{{nome}}
        ports:
            - "{{portaPma}}:80"
        environment:
            PMA_HOST: db-{{nome}}
            PMA_PORT: 3306
            UPLOAD_LIMIT: 500M
        networks:
            - docker-rede
        depends_on:
            - "mysql"
        restart: always
networks:
    docker-rede:
        driver: bridge
