<?php

return (new \DataBase\DataBase())
    ->id()
    ->int('id_admin_empresa')->tamanho(9)

    ->int('usuario')->tamanho(9)
    ->int('status_ativo')->tamanho(9)
    ->int('status_inativo')->tamanho(9)
    ->int('status_bloqueado')->tamanho(9)

    ->int('estado_civil_solteiro')->tamanho(9)
    ->int('estado_civil_casado')->tamanho(9)
    ->int('estado_civil_divorciado')->tamanho(9)
    ->int('estado_civil_viuvo')->tamanho(9)
    ->int('estado_civil_separado')->tamanho(9)
    ->int('estado_civil_sem_dado')->tamanho(9)

    ->int('genero_masculino')->tamanho(9)
    ->int('genero_feminino')->tamanho(9)
    ->int('genero_feminino')->tamanho(9)
    ->int('genero_outro')->tamanho(9)
    ->int('genero_nao_informado')->tamanho(9)
    ->int('genero_sem_dado')->tamanho(9)

    ->int('dado_3_meses')->tamanho(9)
    ->int('dado_6_meses')->tamanho(9)
    ->int('dado_9_meses')->tamanho(9)
    ->int('dado_12_meses')->tamanho(9)

    ->int('idade_ate_20')->tamanho(9)
    ->int('idade_ate_30')->tamanho(9)
    ->int('idade_ate_40')->tamanho(9)
    ->int('idade_ate_50')->tamanho(9)
    ->int('idade_ate_60')->tamanho(9)
    ->int('idade_mais_60')->tamanho(9)
    ->int('idade_sem_dado')->tamanho(9)

    ->int('situacao_ativo')->tamanho(9)
    ->int('situacao_aposentado')->tamanho(9)
    ->int('situacao_pensionista')->tamanho(9)
    ->int('situacao_cedido')->tamanho(9)
    ->int('situacao_excedente')->tamanho(9)
    ->int('situacao_sem_dado')->tamanho(9)

    ->int('uf_ac_ativo')->tamanho(9)
    ->int('uf_ac_inativo')->tamanho(9)
    ->int('uf_al_ativo')->tamanho(9)
    ->int('uf_al_inativo')->tamanho(9)
    ->int('uf_ap_ativo')->tamanho(9)
    ->int('uf_ap_inativo')->tamanho(9)
    ->int('uf_am_ativo')->tamanho(9)
    ->int('uf_am_inativo')->tamanho(9)
    ->int('uf_ba_ativo')->tamanho(9)
    ->int('uf_ba_inativo')->tamanho(9)
    ->int('uf_ce_ativo')->tamanho(9)
    ->int('uf_ce_inativo')->tamanho(9)
    ->int('uf_df_ativo')->tamanho(9)
    ->int('uf_df_inativo')->tamanho(9)
    ->int('uf_es_ativo')->tamanho(9)
    ->int('uf_es_inativo')->tamanho(9)
    ->int('uf_go_ativo')->tamanho(9)
    ->int('uf_go_inativo')->tamanho(9)
    ->int('uf_ma_ativo')->tamanho(9)
    ->int('uf_ma_inativo')->tamanho(9)
    ->int('uf_mt_ativo')->tamanho(9)
    ->int('uf_mt_inativo')->tamanho(9)
    ->int('uf_ms_ativo')->tamanho(9)
    ->int('uf_ms_inativo')->tamanho(9)
    ->int('uf_mg_ativo')->tamanho(9)
    ->int('uf_mg_inativo')->tamanho(9)
    ->int('uf_pa_ativo')->tamanho(9)
    ->int('uf_pa_inativo')->tamanho(9)
    ->int('uf_pb_ativo')->tamanho(9)
    ->int('uf_pb_inativo')->tamanho(9)
    ->int('uf_pr_ativo')->tamanho(9)
    ->int('uf_pr_inativo')->tamanho(9)
    ->int('uf_pe_ativo')->tamanho(9)
    ->int('uf_pe_inativo')->tamanho(9)
    ->int('uf_pi_ativo')->tamanho(9)
    ->int('uf_pi_inativo')->tamanho(9)
    ->int('uf_rj_ativo')->tamanho(9)
    ->int('uf_rj_inativo')->tamanho(9)
    ->int('uf_rn_ativo')->tamanho(9)
    ->int('uf_rn_inativo')->tamanho(9)
    ->int('uf_rs_ativo')->tamanho(9)
    ->int('uf_rs_inativo')->tamanho(9)
    ->int('uf_ro_ativo')->tamanho(9)
    ->int('uf_ro_inativo')->tamanho(9)
    ->int('uf_rr_ativo')->tamanho(9)
    ->int('uf_rr_inativo')->tamanho(9)
    ->int('uf_sc_ativo')->tamanho(9)
    ->int('uf_sc_inativo')->tamanho(9)
    ->int('uf_sp_ativo')->tamanho(9)
    ->int('uf_sp_inativo')->tamanho(9)
    ->int('uf_se_ativo')->tamanho(9)
    ->int('uf_se_inativo')->tamanho(9)
    ->int('uf_tp_ativo')->tamanho(9)
    ->int('uf_tp_inativo')->tamanho(9)

    ->date('data_acesso')
    ->datetime('data_atualizacao');
