APP_URL=["login.local"]
APP_TIPO=localhost

SECURITY_POLICY=default-src 'self'

ROTA_PRINCIPAL=oauth
ROTA_BLOQUEADA=["painel","site","api","cdn"]

LINK_ARQUIVO=https://arquivo.marktclub.com.br

DB_STATUS=localhost
DB_ESCRITA=db-marktclub
DB_LEITURA=db-marktclub
DB_BANCO=marktclub
DB_USUARIO=root
DB_SENHA=123456

FENAE_CLIENT_ID=
FENAE_CLIENT_SECRET=
FENAE_LINK_CONFIGURACAO=
FENAE_REDIRECT_URI=
FENAE_LOGIN=
FENAE_LOGOUT_REDIRECT_URI=
FENAE_POST_LOGOUT_REDIRECT_URI=
FENAE_LOGOUT_CLUBE=
FENAE_SCOPE=
FENAE_CLUBE=
