<?php

return (new \DataBase\DataBase())
    ->id()
    ->uuid()
    ->int('id_admin_empresa')->tamanho(9)
    ->int('id_usuario_equipe')->tamanho(9)
    ->varchar('titulo_grande')->tamanho(250)
    ->varchar('titulo_pequeno')->tamanho(80)->null()
    ->varchar('subtitulo')->tamanho(250)->null()
    ->text('texto_grande')
    ->varchar('texto_pequeno')->tamanho(120)->null()
    ->imagem('imagem_grande')->null()
    ->imagem('imagem_pequena')->null()
    ->json('imagem_galeria')->null()
    ->imagem('imagem_social')->null()
    ->json('arquivo')->null()
    ->varchar('fonte_noticia')->tamanho(100)->null()
    ->text('fonte_link')->null()
    ->varchar('autor_noticia')->tamanho(100)->null()
    ->dataCriacao()
    ->dataAtualizacao()
    ->slug('url', 'titulo_pequeno')
    ->datetime('data_publicacao_inicio')
    ->datetime('data_publicacao_final')->null()
    ->datetime('data_publicacao_atualizacao')->null()
    ->int('permissao_restrita')->tamanho(1)->null()
    ->int('permissao_site')->tamanho(1)->null()
    ->int('permissao_banner')->tamanho(1)->null()
    ->status();
