<?php

use App\Classes\Painel\Config\Padrao;

$permissao = (new Padrao())->permissao();

return [
    [
        'id'                => 1,
        'uuid'              => '8fd85f9f7cc21d6e33399681d6e5fca7',
        'id_admin_empresa'  => '1',
        'tipo'              => '1',
        'nome_perfil'       => 'andre.rodrigues',
        'nome_real'         => 'Andre Rodrigues',
        'documento_cpf'     => '01495180131',
        'email_pessoal'     => null,
        'email_trabalho'    => 'andre@marktclub.com.br',
        'telefone_pessoal'  => '61981777773',
        'telefone_trabalho' => null,
        'imagem_arquivo'    => null,
        'imagem_facebook'   => 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=5551849098231280&amp;height=300&amp;width=300&amp;ext=1667480926&amp;hash=AeToGj-DscG42CxRlWE',
        'imagem_google'     => 'https://lh3.googleusercontent.com/a-/ACNPEu9u23_b1dR1oh-m6aMiCBeQsTPShZX3auQMmTyhhfs=s384-c',
        'imagem_tipo'       => '2',
        'permissao'         => $permissao,
        'salt'              => password('Teste@1324'),
        'marktclub'         => 1,
        'desenvolvedor'     => 1,
        'gerente'           => 1,
        'admin'             => 1,
        'status'            => '1'
    ],
    [
        'id'                => 2,
        'uuid'              => 'f9cff03397e1be63c18772fccd298cdc',
        'id_admin_empresa'  => '1',
        'tipo'              => '2',
        'nome_perfil'       => 'roberto.camilo',
        'nome_real'         => 'Roberto Niwa Camilo',
        'documento_cpf'     => '92606290470',
        'email_pessoal'     => null,
        'email_trabalho'    => 'roberto@markt.club',
        'telefone_pessoal'  => null,
        'telefone_trabalho' => null,
        'imagem_arquivo'    => null,
        'imagem_facebook'   => null,
        'imagem_google'     => null,
        'imagem_tipo'       => null,
        'permissao'         => $permissao,
        'desenvolvedor'     => null,
        'gerente'           => null,
        'admin'             => null,
        'status'            => '1'
    ],
    [
        'id'               => 3,
        'uuid'             => '5d608f97-1e64-4aba-9b94-2ba1c6376db5',
        'id_admin_empresa' => 1,
        'tipo'             => 3,
        'nome_perfil'      => 'markt.club',
        'nome_real'        => 'Markt Club',
        'email_trabalho'   => 'app@marktclub.com.br',
        'telefone_pessoal' => '61900001234',
        'documento_cpf'    => '01234567890',
        'salt'             => password('Teste@1324'),
        'permissao'        => $permissao,
        'primeiro_acesso'  => null,
        'mudar_senha'      => null,
        'desenvolvedor'    => 1,
        'marktclub'        => 1,
        'admin'            => 1,
        'gerente'          => 1,
        'status'           => 1,
    ],
    [
        'uuid'              => '3df1a38ec0919bd14162beabb73e12b4',
        'id_admin_empresa'  => '1',
        'tipo'              => '1',
        'nome_perfil'       => 'herisson.gomes',
        'nome_real'         => 'HÉRISSON GOMES',
        'documento_cpf'     => '82194545476',
        'email_pessoal'     => null,
        'email_trabalho'    => 'herisson@markt.club',
        'telefone_pessoal'  => null,
        'telefone_trabalho' => null,
        'imagem_arquivo'    => null,
        'imagem_facebook'   => null,
        'imagem_google'     => null,
        'imagem_tipo'       => null,
        'permissao'         => $permissao,
        'desenvolvedor'     => null,
        'gerente'           => null,
        'admin'             => null,
        'status'            => '1'
    ],
    [
        'uuid'              => '0b077500f13856833d1d62bebceac6eb',
        'id_admin_empresa'  => '1',
        'tipo'              => '1',
        'nome_perfil'       => 'flavia.pinheiro',
        'nome_real'         => 'FLAVIA DANIELA PINHEIRO',
        'documento_cpf'     => '57880598790',
        'email_pessoal'     => null,
        'email_trabalho'    => 'flavia@markt.club',
        'telefone_pessoal'  => null,
        'telefone_trabalho' => null,
        'imagem_arquivo'    => null,
        'imagem_facebook'   => null,
        'imagem_google'     => null,
        'imagem_tipo'       => null,
        'permissao'         => $permissao,
        'desenvolvedor'     => null,
        'gerente'           => null,
        'admin'             => null,
        'status'            => '1'
    ],
    [
        'uuid'              => '060d9bc1e911b67a6c80d0dbf403ca14',
        'id_admin_empresa'  => '1',
        'tipo'              => '3',
        'nome_perfil'       => 'isabella.queiroz',
        'nome_real'         => 'ISABELLA QUEIROZ',
        'documento_cpf'     => '05174475688',
        'email_pessoal'     => null,
        'email_trabalho'    => 'isabella@markt.club',
        'telefone_pessoal'  => null,
        'telefone_trabalho' => null,
        'imagem_arquivo'    => null,
        'imagem_facebook'   => null,
        'imagem_google'     => null,
        'imagem_tipo'       => null,
        'permissao'         => $permissao,
        'desenvolvedor'     => null,
        'gerente'           => null,
        'admin'             => null,
        'status'            => '1'
    ],
    [
        'uuid'              => '0f3a5572ba1343afca4c0b538354c59c',
        'id_admin_empresa'  => '1',
        'tipo'              => '1',
        'nome_perfil'       => 'albert.dias',
        'nome_real'         => 'Albert Dias',
        'documento_cpf'     => '62581868589',
        'email_pessoal'     => null,
        'email_trabalho'    => 'albert.dias@markt.club',
        'telefone_pessoal'  => null,
        'telefone_trabalho' => null,
        'imagem_arquivo'    => null,
        'imagem_facebook'   => null,
        'imagem_google'     => null,
        'imagem_tipo'       => null,
        'permissao'         => $permissao,
        'desenvolvedor'     => null,
        'gerente'           => null,
        'admin'             => null,
        'status'            => '1'
    ],
    [
        'uuid'              => 'a014996d75cb01f470dfc21c1f60c6d3',
        'id_admin_empresa'  => '1',
        'tipo'              => '1',
        'nome_perfil'       => 'Codestep',
        'nome_real'         => 'Codestep Engine',
        'documento_cpf'     => '12345678900',
        'email_pessoal'     => null,
        'email_trabalho'    => 'lucas.alves@markt.club',
        'telefone_pessoal'  => null,
        'telefone_trabalho' => null,
        'imagem_arquivo'    => null,
        'imagem_facebook'   => null,
        'imagem_google'     => 'https://lh3.googleusercontent.com/a-/ACNPEu-xUX6zA-hZissHFCJPq8k6uFQfX5u1EBEu31vP=s384-c',
        'imagem_tipo'       => '2',
        'permissao'         => $permissao,
        'salt'              => password('Teste@3060'),
        'desenvolvedor'     => '1',
        'gerente'           => '1',
        'admin'             => '1',
        'status'            => '1'
    ],
    [
        'uuid'             => '96f5027d-c516-4674-9556-e28f9e542cd6',
        'id_admin_empresa' => 2,
        'tipo'             => 3,
        'nome_perfil'      => 'anafe.card',
        'nome_real'        => 'Aanfe Card',
        'email_trabalho'   => 'testeteste@anafecard.com.br',
        'telefone_pessoal' => '61900001234',
        'documento_cpf'    => '01234567892',
        'salt'             => password('Teste@1324'),
        'permissao'        => $permissao,
        'primeiro_acesso'  => null,
        'mudar_senha'      => null,
        'desenvolvedor'    => 1,
        'marktclub'        => null,
        'admin'            => 1,
        'gerente'          => 1,
        'status'           => 1,
    ],
    [
        'uuid'                => uuid(),
        'id_admin_empresa'    => 1,
        'id_admin_subempresa' => 1,
        'tipo'                => 3,
        'nome_perfil'         => 'markt.club.2',
        'nome_real'           => 'Markt Club 2',
        'email_trabalho'      => 'app@marktclub2.com.br',
        'telefone_pessoal'    => '61900001234',
        'documento_cpf'       => '01234567891',
        'salt'                => password('Teste@1324'),
        'permissao'           => $permissao,
        'primeiro_acesso'     => null,
        'mudar_senha'         => null,
        'desenvolvedor'       => null,
        'marktclub'           => null,
        'admin'               => null,
        'gerente'             => null,
        'status'              => 1,
    ],
    [
        'uuid'             => 'b1923bd1-6cf8-405a-886b-38799acbbdf3',
        'id_admin_empresa' => '2',
        'tipo'             => '1',
        'nome_real'        => 'Usuário Empresa 2',
        'documento_cpf'    => '22222222222',
        'email_pessoal'    => null,
        'email_trabalho'   => emailAleatorio(),
        'telefone_pessoal' => telefoneAleatorio(),
        'permissao'        => $permissao,
        'salt'             => password('Teste@1324'),
        'desenvolvedor'    => null,
        'gerente'          => null,
        'admin'            => null,
        'status'           => '1'
    ],
];
