<?php

return [
    [
        'uuid'             => uuid(),
        'id_admin_empresa' => jsonEncode([1]),
        'titulo_painel'    => 'Popup para titular',
        'usuario_tipo'     => jsonEncode([1]),
        'slug'             => 'popup-para-titular',
        'imagem'           => null,
        'titulo'           => 'Popup apenas para titular',
        'texto'            => 'Texto do popup de teste 01',
        'regulamento'      => 'Regulamento do popup de teste 01',
        'data_inicio'      => dataPassadaAleatorio(),
        'data_final'       => dataFuturaAleatorio(),
        'atualizar_dado'   => null,
        'botao_texto'      => 'Abrir Google',
        'botao_link'       => 'https://google.com',
        'botao_target'     => 2,
        'status'           => 1
    ],
    [
        'uuid'             => uuid(),
        'id_admin_empresa' => jsonEncode([1]),
        'titulo_painel'   => 'Popup para dependente',
        'usuario_tipo'     => jsonEncode([2]),
        'slug'             => 'popup-para-dependente',
        'imagem'           => null,
        'titulo'           => 'Popup apenas para dependete',
        'texto'            => 'Texto do popup de teste 01',
        'regulamento'      => 'Regulamento do popup de teste 01',
        'data_inicio'      => dataPassadaAleatorio(),
        'data_final'       => dataFuturaAleatorio(),
        'atualizar_dado'   => null,
        'botao_texto'      => 'Abrir Google',
        'botao_link'       => 'https://google.com',
        'botao_target'     => 2,
        'status'           => 1
    ],
    [
        'uuid'             => uuid(),
        'id_admin_empresa' => jsonEncode([1]),
        'titulo_painel'    => 'Popup para ambos',
        'slug'             => 'popup-para-ambos',
        'imagem'           => null,
        'titulo'           => 'Popup para titular e dependente',
        'texto'            => 'Texto do popup de teste 01',
        'regulamento'      => 'Regulamento do popup de teste 01',
        'data_inicio'      => dataPassadaAleatorio(),
        'data_final'       => dataFuturaAleatorio(),
        'atualizar_dado'   => null,
        'botao_texto'      => 'Abrir Google',
        'botao_link'       => 'https://google.com',
        'botao_target'     => 2,
        'status'           => 1
    ],
    [
        'uuid'             => uuid(),
        'id_admin_empresa' => jsonEncode([1]),
        'slug'             => 'popup-sem-usuario-tipo',
        'titulo_painel'    => 'Popup sem usuario tipo',
        'imagem'           => null,
        'titulo'           => 'Popup sem usuario tipo',
        'texto'            => 'Texto do popup de teste 01',
        'regulamento'      => 'Regulamento do popup de teste 01',
        'data_inicio'      => dataPassadaAleatorio(),
        'data_final'       => dataFuturaAleatorio(),
        'atualizar_dado'   => null,
        'botao_texto'      => 'Abrir Google',
        'botao_link'       => 'https://google.com',
        'botao_target'     => 2,
        'status'           => 1
    ]
];
