<?php

namespace App\Models\Api\UsuarioCliente\Trait;

trait DadoInicialRotina
{
    private function montarDadoInicial()
    {
        foreach ($this->empresaValida as $id) {
            $this->dado[$id] = [
                'id_admin_empresa' => $id,
                'usuario' => 0,
                'status_ativo' => 0,
                'status_inativo' => 0,
                'status_bloqueado' => 0,
                'estado_civil_solteiro' => 0,
                'estado_civil_casado' => 0,
                'estado_civil_divorciado' => 0,
                'estado_civil_viuvo' => 0,
                'estado_civil_separado' => 0,
                'estado_civil_sem_dado' => 0,
                'genero_masculino' => 0,
                'genero_feminino' => 0,
                'genero_feminino' => 0,
                'genero_outro' => 0,
                'genero_nao_informado' => 0,
                'genero_sem_dado' => 0,
                'dado_3_meses' => 0,
                'dado_6_meses' => 0,
                'dado_9_meses' => 0,
                'dado_12_meses' => 0,
                'idade_ate_20' => 0,
                'idade_ate_30' => 0,
                'idade_ate_40' => 0,
                'idade_ate_50' => 0,
                'idade_ate_60' => 0,
                'idade_mais_60' => 0,
                'idade_sem_dado' => 0,
                'situacao_ativo' => 0,
                'situacao_aposentado' => 0,
                'situacao_pensionista' => 0,
                'situacao_cedido' => 0,
                'situacao_excedente' => 0,
                'situacao_sem_dado' => 0,
                'uf_ac_ativo' => 0,
                'uf_ac_inativo' => 0,
                'uf_al_ativo' => 0,
                'uf_al_inativo' => 0,
                'uf_ap_ativo' => 0,
                'uf_ap_inativo' => 0,
                'uf_am_ativo' => 0,
                'uf_am_inativo' => 0,
                'uf_ba_ativo' => 0,
                'uf_ba_inativo' => 0,
                'uf_ce_ativo' => 0,
                'uf_ce_inativo' => 0,
                'uf_df_ativo' => 0,
                'uf_df_inativo' => 0,
                'uf_es_ativo' => 0,
                'uf_es_inativo' => 0,
                'uf_go_ativo' => 0,
                'uf_go_inativo' => 0,
                'uf_ma_ativo' => 0,
                'uf_ma_inativo' => 0,
                'uf_mt_ativo' => 0,
                'uf_mt_inativo' => 0,
                'uf_ms_ativo' => 0,
                'uf_ms_inativo' => 0,
                'uf_mg_ativo' => 0,
                'uf_mg_inativo' => 0,
                'uf_pa_ativo' => 0,
                'uf_pa_inativo' => 0,
                'uf_pb_ativo' => 0,
                'uf_pb_inativo' => 0,
                'uf_pr_ativo' => 0,
                'uf_pr_inativo' => 0,
                'uf_pe_ativo' => 0,
                'uf_pe_inativo' => 0,
                'uf_pi_ativo' => 0,
                'uf_pi_inativo' => 0,
                'uf_rj_ativo' => 0,
                'uf_rj_inativo' => 0,
                'uf_rn_ativo' => 0,
                'uf_rn_inativo' => 0,
                'uf_rs_ativo' => 0,
                'uf_rs_inativo' => 0,
                'uf_ro_ativo' => 0,
                'uf_ro_inativo' => 0,
                'uf_rr_ativo' => 0,
                'uf_rr_inativo' => 0,
                'uf_sc_ativo' => 0,
                'uf_sc_inativo' => 0,
                'uf_sp_ativo' => 0,
                'uf_sp_inativo' => 0,
                'uf_se_ativo' => 0,
                'uf_se_inativo' => 0,
                'uf_tp_ativo' => 0,
                'uf_tp_inativo' => 0,
                'data_acesso' => 0,
            ];
        }
    }
}
