<?php

return (new \DataBase\DataBase())
    ->id()
    ->uuid()
    ->int('id_admin_empresa')->relacionado(TABELA_COMERCIAL_EMPRESA, 'id')
    ->int('id_usuario_equipe')->relacionado(TABELA_USUARIO_EQUIPE, 'id')
    ->varchar('titulo')->tamanho(100)
    ->text('texto')->null()
    ->int('area')
    ->int('tipo')
    ->json('tarefa_tipo')->null()
    ->json('arquivo')->null()
    ->json('seguindo')->null()
    ->int('com_prazo')->null()
    ->date('data_entrega')->null()
    ->date('data_entrega_real')->null()
    ->int('ordem')->null()
    ->dataCriacao()
    ->dataAtualizacao()
    ->status();
