<?php

$data = hoje();
return [
    ['id' => '1', 'id_admin_empresa' => '1', 'quantidade' => '16', 'os' => 'Android', 'data_acesso' => dataRemover($data, 8, 'dia')],
    ['id' => '2', 'id_admin_empresa' => '1', 'quantidade' => '30', 'os' => 'Linux', 'data_acesso' => dataRemover($data, 8, 'dia')],
    ['id' => '3', 'id_admin_empresa' => '1', 'quantidade' => '28', 'os' => 'Windows', 'data_acesso' => dataRemover($data, 8, 'dia')],
    ['id' => '4', 'id_admin_empresa' => '1', 'quantidade' => '21', 'os' => 'IOS', 'data_acesso' => dataRemover($data, 8, 'dia')],
    ['id' => '5', 'id_admin_empresa' => '1', 'quantidade' => '27', 'os' => 'MAC', 'data_acesso' => dataRemover($data, 8, 'dia')],
    ['id' => '6', 'id_admin_empresa' => '1', 'quantidade' => '26', 'os' => 'Android', 'data_acesso' => dataRemover($data, 7, 'dia')],
    ['id' => '7', 'id_admin_empresa' => '1', 'quantidade' => '28', 'os' => 'Windows', 'data_acesso' => dataRemover($data, 7, 'dia')],
    ['id' => '8', 'id_admin_empresa' => '1', 'quantidade' => '32', 'os' => 'MAC', 'data_acesso' => dataRemover($data, 7, 'dia')],
    ['id' => '9', 'id_admin_empresa' => '1', 'quantidade' => '25', 'os' => 'IOS', 'data_acesso' => dataRemover($data, 7, 'dia')],
    ['id' => '10', 'id_admin_empresa' => '1', 'quantidade' => '32', 'os' => 'Linux', 'data_acesso' => dataRemover($data, 7, 'dia')],
    ['id' => '11', 'id_admin_empresa' => '1', 'quantidade' => '37', 'os' => 'MAC', 'data_acesso' => dataRemover($data, 6, 'dia')],
    ['id' => '12', 'id_admin_empresa' => '1', 'quantidade' => '31', 'os' => 'Linux', 'data_acesso' => dataRemover($data, 6, 'dia')],
    ['id' => '13', 'id_admin_empresa' => '1', 'quantidade' => '23', 'os' => 'IOS', 'data_acesso' => dataRemover($data, 6, 'dia')],
    ['id' => '14', 'id_admin_empresa' => '1', 'quantidade' => '39', 'os' => 'Android', 'data_acesso' => dataRemover($data, 6, 'dia')],
    ['id' => '15', 'id_admin_empresa' => '1', 'quantidade' => '29', 'os' => 'Windows', 'data_acesso' => dataRemover($data, 6, 'dia')],
    ['id' => '16', 'id_admin_empresa' => '1', 'quantidade' => '40', 'os' => 'MAC', 'data_acesso' => dataRemover($data, 5, 'dia')],
    ['id' => '17', 'id_admin_empresa' => '1', 'quantidade' => '33', 'os' => 'Windows', 'data_acesso' => dataRemover($data, 5, 'dia')],
    ['id' => '18', 'id_admin_empresa' => '1', 'quantidade' => '49', 'os' => 'Android', 'data_acesso' => dataRemover($data, 5, 'dia')],
    ['id' => '19', 'id_admin_empresa' => '1', 'quantidade' => '36', 'os' => 'Linux', 'data_acesso' => dataRemover($data, 5, 'dia')],
    ['id' => '20', 'id_admin_empresa' => '1', 'quantidade' => '28', 'os' => 'IOS', 'data_acesso' => dataRemover($data, 5, 'dia')],
    ['id' => '21', 'id_admin_empresa' => '1', 'quantidade' => '32', 'os' => 'Windows', 'data_acesso' => dataRemover($data, 4, 'dia')],
    ['id' => '22', 'id_admin_empresa' => '1', 'quantidade' => '41', 'os' => 'Android', 'data_acesso' => dataRemover($data, 4, 'dia')],
    ['id' => '23', 'id_admin_empresa' => '1', 'quantidade' => '36', 'os' => 'IOS', 'data_acesso' => dataRemover($data, 4, 'dia')],
    ['id' => '24', 'id_admin_empresa' => '1', 'quantidade' => '36', 'os' => 'MAC', 'data_acesso' => dataRemover($data, 4, 'dia')],
    ['id' => '25', 'id_admin_empresa' => '1', 'quantidade' => '30', 'os' => 'Linux', 'data_acesso' => dataRemover($data, 4, 'dia')],
    ['id' => '26', 'id_admin_empresa' => '1', 'quantidade' => '38', 'os' => 'Linux', 'data_acesso' => dataRemover($data, 3, 'dia')],
    ['id' => '27', 'id_admin_empresa' => '1', 'quantidade' => '29', 'os' => 'IOS', 'data_acesso' => dataRemover($data, 3, 'dia')],
    ['id' => '28', 'id_admin_empresa' => '1', 'quantidade' => '34', 'os' => 'MAC', 'data_acesso' => dataRemover($data, 3, 'dia')],
    ['id' => '29', 'id_admin_empresa' => '1', 'quantidade' => '38', 'os' => 'Android', 'data_acesso' => dataRemover($data, 3, 'dia')],
    ['id' => '30', 'id_admin_empresa' => '1', 'quantidade' => '34', 'os' => 'Windows', 'data_acesso' => dataRemover($data, 3, 'dia')],
    ['id' => '31', 'id_admin_empresa' => '1', 'quantidade' => '34', 'os' => 'IOS', 'data_acesso' => dataRemover($data, 2, 'dia')],
    ['id' => '32', 'id_admin_empresa' => '1', 'quantidade' => '39', 'os' => 'Android', 'data_acesso' => dataRemover($data, 2, 'dia')],
    ['id' => '33', 'id_admin_empresa' => '1', 'quantidade' => '28', 'os' => 'Linux', 'data_acesso' => dataRemover($data, 2, 'dia')],
    ['id' => '34', 'id_admin_empresa' => '1', 'quantidade' => '33', 'os' => 'MAC', 'data_acesso' => dataRemover($data, 2, 'dia')],
    ['id' => '35', 'id_admin_empresa' => '1', 'quantidade' => '22', 'os' => 'Windows', 'data_acesso' => dataRemover($data, 2, 'dia')],
    ['id' => '36', 'id_admin_empresa' => '1', 'quantidade' => '34', 'os' => 'IOS', 'data_acesso' => dataRemover($data, 1, 'dia')],
    ['id' => '37', 'id_admin_empresa' => '1', 'quantidade' => '31', 'os' => 'Android', 'data_acesso' => dataRemover($data, 1, 'dia')],
    ['id' => '38', 'id_admin_empresa' => '1', 'quantidade' => '22', 'os' => 'MAC', 'data_acesso' => dataRemover($data, 1, 'dia')],
    ['id' => '39', 'id_admin_empresa' => '1', 'quantidade' => '25', 'os' => 'Linux', 'data_acesso' => dataRemover($data, 1, 'dia')],
    ['id' => '40', 'id_admin_empresa' => '1', 'quantidade' => '29', 'os' => 'Windows', 'data_acesso' => dataRemover($data, 1, 'dia')]
];
