<?php

return [
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 10),
        'empresa'                    => rand(1, 20),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio([
            'MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO'
        ]),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 1
    ],
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 10),
        'empresa'                    => rand(1, 15),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio(['MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO']),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 2,
    ],
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 50),
        'empresa'                    => rand(1, 10),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio([
            'MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO'
        ]),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 2
    ],
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 50),
        'empresa'                    => rand(1, 20),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio([
            'MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO'
        ]),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 2
    ],
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 60),
        'empresa'                    => rand(1, 5),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio([
            'MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO'
        ]),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 2
    ],
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 55),
        'empresa'                    => rand(1, 20),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio([
            'MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO'
        ]),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 2
    ],
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 10),
        'empresa'                    => rand(1, 10),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio([
            'MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO'
        ]),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 2
    ],
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 10),
        'empresa'                    => rand(1, 100),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio([
            'MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO'
        ]),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 2
    ],
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 15),
        'empresa'                    => rand(1, 15),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio([
            'MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO'
        ]),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 2
    ],
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 25),
        'empresa'                    => rand(1, 35),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio([
            'MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO'
        ]),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 2
    ],
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 40),
        'empresa'                    => rand(1, 45),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio([
            'MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO'
        ]),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 2
    ],
    [
        'cod'                        => uuid(),
        'usuario'                    => rand(1, 55),
        'empresa'                    => rand(1, 85),
        'documento_cpf'              => cpfAleatorio(),
        'valor'                      => rand(10000000, 99999999),
        'estado_civil'               => estadoCivilAleatorio(),
        'documento_rg'               => rgAleatorio(),
        'data_nascimento'            => dataPassadaAleatorio(),
        'cep'                        => cepAleatorio(),
        'estado'                     => estadoAleatorio(),
        'cidade'                     => cidadeAleatorio(estadoAleatorio()),
        'bairro'                     => bairroAleatorio(),
        'numero'                     => rand(1, 100),
        'logradouro'                 => logradouroAleatorio(),
        'complemento'                => complementoAleatorio(),
        'dependente_cpf'             => cpfAleatorio(),
        'dependente_nome'            => nomeCompletoAleatorio(),
        'dependente_grau_parentesco' => valorAleatorio([
            'MÃE', 'PAI', 'FILHO', 'TIO', 'TIA', 'AVÔ', 'AVÓ', 'PRIMO'
        ]),
        'dependente_rg'              => rgAleatorio(),
        'dependente_data_nascimento' => dataPassadaAleatorio(),
        'data_validacao'             => dataFuturaAleatorio(),
        'status'                     => 2
    ]
];
