<?php

return (new \DataBase\DataBase())
    ->id()
    ->char('cod')->tamanho(36)
    ->json('empresa')
    ->json('destaque')
    ->int('categoria_principal')->tamanho(2)
    ->json('categoria_todas')
    ->char('titulo')->tamanho(36)
    ->varchar('url')
    ->imagem('imagem')->tamanho(136)
    ->imagem('banner')->tamanho(136)->null()
    ->varchar('desconto')
    ->text('desconto_texto')->null()
    ->text('procedimento_texto')->null()
    ->text('voucher_texto')->null()
    ->dataCriacao()
    ->dataAtualizacao()
    ->date('data_contrato_inicio')->null()
    ->int('estabelecimento')->tamanho(1)->null()
    ->int('tipo')->tamanho(1)->null()
    ->int('limite_voucher')->tamanho(5)->null()
    ->int('prazo_voucher')->tamanho(5)->null()
    ->date('prazo_voucher_fixo')->null()
    ->status()->null()
    ->varchar('descricao')->tamanho(255)->null()
    ->int('favorito')->tamanho(1)->null();
