<?php

return [
    [
        'id' => 2,
        'cod' => '890713a200a9e45aa85e2ae67aa41e74',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'SalaVip Anafe',
        'url' => 'salavip-anafe',
        'imagem' => 'salavip.png',
        'desconto' => '50% ou 100% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["2"],
        'empresa' => ["2"],
        'status' => 4
    ],
    [
        'id' => 8074,
        'cod' => '9792e058562303f9e7e0604c5117c569',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'SalaVip Anape',
        'url' => 'salavip-anape',
        'imagem' => 'salavip.png',
        'desconto' => '50% ou 100% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["66"],
        'empresa' => ["66"],
        'status' => 4
    ],
    [
        'cod' => '5d20bebb-36d5-47ce-8bc8-178309983a9a',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Parceiro Voucher Criado',
        'url' => 'parceiro-voucher-criado',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'status' => 4
    ],
    [
        'id' => 1,
        'cod' => 'f10e05c0-5b02-4bff-8e22-719a8797f0d6',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Parceiro Normal',
        'url' => 'parceiro-normal',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'status' => 4
    ],
    [
        'id' => 3,
        'cod' => '4502e7e8-9359-470e-9588-0a1501449675',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Parceiro com limite',
        'url' => 'parceiro-limite',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'limite_voucher' => 1,
        'status' => 4
    ],
    [
        'id' => 4,
        'cod' => 'adca39ea4a6d6bcc51eba8afcdb54eaa',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Parceiro com prazo',
        'url' => 'parceiro-prazo',
        'imagem' => 'parceiro.png',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'desconto' => '10% de desconto',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'limite_voucher' => 10,
        'prazo_voucher' => 5,
        'status' => 4
    ],
    [
        'id' => 5,
        'cod' => 'f9cbb6ae-b847-43cf-b9b8-6f72b67789df',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Parceiro com prazo fixo',
        'url' => 'parceiro-prazo-fixo',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'prazo_voucher_fixo' => dataAdicionar(hoje(), 60, 'dias'),
        'status' => 4
    ],
    [
        'id' => 4207,
        'cod' => 'ca0bde20602db3ec777acbbcfb5a4c61',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Blue Fit',
        'url' => 'bluefit',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'prazo_voucher_fixo' => '2040-01-01',
        'status' => 4
    ],
    [
        'id' => 15612,
        'cod' => 'ca0bde20602db3ec777acbbcfb5a4c62',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Madruga App de Mobilidade',
        'url' => 'madruga',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'prazo_voucher_fixo' => dataAdicionar(hoje(), 60, 'dias'),
        'status' => 4
    ],
    [
        'id' => 100,
        'cod' => '7b1476c3-2627-490c-a0cf-dff7b9196b45',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Parceiro premium 01',
        'url' => 'premium-01',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "1967"],
        'empresa' => ["1", "1967"],
        'prazo_voucher' => 5,
        'limite_voucher' => 5,
        'status' => 5
    ],
    [
        'id' => 101,
        'cod' => '7b1476c3-2627-490c-a0cf-dff7b9196b46',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Parceiro premium 02',
        'url' => 'premium-02',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "1967"],
        'empresa' => ["1", "1967"],
        'prazo_voucher' => 5,
        'limite_voucher' => 5,
        'status' => 5
    ],
    [
        'id' => 102,
        'cod' => '7b1476c3-2627-490c-a0cf-dff7b9196b47',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Parceiro premium 03',
        'url' => 'premium-03',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "1967"],
        'empresa' => ["1", "1967"],
        'prazo_voucher' => 5,
        'limite_voucher' => 5,
        'status' => 5
    ],
    [
        'id' => 103,
        'cod' => '7b1476c3-2627-490c-a0cf-dff7b9196b48',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Parceiro premium 04',
        'url' => 'premium-04',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "1967"],
        'empresa' => ["1", "1967"],
        'prazo_voucher' => 5,
        'limite_voucher' => 5,
        'status' => 5
    ],
    [
        'id' => 104,
        'cod' => '7b1476c3-2627-490c-a0cf-dff7b9196b49',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Parceiro premium 05',
        'url' => 'premium-05',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "1967"],
        'empresa' => ["1", "1967"],
        'prazo_voucher' => 5,
        'limite_voucher' => 3,
        'status' => 5
    ],
    [
        'cod' => '7b1476c3-2627-490c-a0cf-dff7b9196b00',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Parceiro premium 06',
        'url' => 'premium-06',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "1967"],
        'empresa' => ["1", "1967"],
        'prazo_voucher' => 5,
        'limite_voucher' => 3,
        'status' => 5
    ],
    [
        'cod' => 'f98e10ebc70e101c9d5d6fcf766d5320',
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'UBER - Renner',
        'url' => 'uber-renner',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'status' => 4
    ],
    [
        'cod' => uuid(),
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Pague Menos',
        'url' => 'pague-menos',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'tipo' => 3,
        'estabelecimento' => 1,
        'status' => 4
    ],
    [
        'cod' => uuid(),
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Drograria Online',
        'url' => 'drograria-online',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'tipo' => 3,
        'estabelecimento' => 2,
        'status' => 4
    ],
    [
        'cod' => uuid(),
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Drograria 2',
        'url' => 'drograria-2',
        'imagem' => 'parceiro.png',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'tipo' => 3,
        'estabelecimento' => 1,
        'status' => 4
    ],
];
