<?php

return [
    [
        'cod' => uuid(),
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Drogaria Online',
        'url' => 'drogaria-online2',
        'imagem' => 'https://arquivo.marktclub.com.br/parceiro/65c3d3b6716418d6425dfa858214a963.jpg',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'tipo' => 3,
        'estabelecimento' => 2,
        'status' => 4,
        'favorito' => numeroAleatorio(0, 1)
    ],
    [
        'cod' => uuid(),
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Pague Menos',
        'url' => 'pague-menos',
        'imagem' => '65c3d3b6716418d6425dfa858214a963.jpg',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'tipo' => 1,
        'estabelecimento' => 1,
        'status' => 4,
        'favorito' => numeroAleatorio(0, 1)
    ],
    [
        'cod' => uuid(),
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'Drogaria Online',
        'url' => 'drogaria-online',
        'imagem' => 'https://arquivo.marktclub.com.br/parceiro/65c3d3b6716418d6425dfa858214a963.jpg',
        'desconto' => '10% de desconto',
        'desconto_texto' => 'Texto de desconto do parceiro',
        'procedimento_texto' => 'Texto de procedimento do parceiro',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'tipo' => 3,
        'estabelecimento' => 2,
        'status' => 4,
        'favorito' => numeroAleatorio(0, 1)
    ],

    [
        'cod' => uuid(),
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'KABUM',
        'url' => '65c3d3b6716418d6425dfa858214a963',
        'imagem' => 'https://arquivo.marktclub.com.br/parceiro/65c3d3b6716418d6425dfa858214a963.jpg',
        'desconto' => '10% de desconto',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'tipo' => 2,
        'estabelecimento' => 1,
        'status' => 4,
        'favorito' => numeroAleatorio(0, 1)
    ],


    [
        'cod' => uuid(),
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'KABUM',
        'url' => '65c3d3b6716418d6425dfa858214a963',
        'imagem' => '65c3d3b6716418d6425dfa858214a963.jpg',
        'desconto' => '10% de desconto',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'tipo' => 1,
        'estabelecimento' => 1,
        'status' => 4,
        'favorito' => numeroAleatorio(0, 1)
    ],

    [
        'cod' => uuid(),
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'KABUM22',
        'url' => '65c3d3b6716418d6425dfa858214a963',
        'imagem' => '65c3d3b6716418d6425dfa858214a963.jpg',
        'desconto' => '10% de desconto',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'tipo' => 1,
        'estabelecimento' => 1,
        'status' => 4,
        'favorito' => numeroAleatorio(0, 1)
    ],

    [
        'cod' => uuid(),
        'categoria_principal' => '1',
        'categoria_todas' => '["1","2","3","4","5","6","7","8"]',
        'titulo' => 'TESTE TESTE',
        'url' => '65c3d3b6716418d6425dfa858214a963',
        'imagem' => '65c3d3b6716418d6425dfa858214a963.jpg',
        'desconto' => '10% de desconto',
        'voucher_texto' => 'Texto para o voucher do parceiro',
        'destaque' => ["1", "2", "66"],
        'empresa' => ["1", "2", "66"],
        'tipo' => 1,
        'estabelecimento' => 1,
        'status' => 4,
        'favorito' => 0
    ],
];
