<?php

$estado = ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'];

return [
    [
        'id'                  => 2,
        'cod'                 => '890713a200a9e45aa85e2ae67aa41e74',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'SalaVip Anafe',
        'url'                 => 'salavip-anafe',
        'imagem'              => 'a82055f1446026f37fda574d337fcf06.png',
        'site'                => 'https://google.com',
        'capa'                => 'a9e26316b4ecec7fad6883f8ad48ca23.jpg',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '50% ou 100% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'procedimento'        => 1,
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'destaque'            => ['2'],
        'empresa'             => ['2'],
        'data_publicacao'     => dataPassadaAleatorio(),
        'estado'              => $estado,
        'tipo'                => 1,
        'status'              => 4
    ],
    [
        'id'                  => 8074,
        'cod'                 => '9792e058562303f9e7e0604c5117c569',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'SalaVip Anape',
        'url'                 => 'salavip-anape',
        'imagem'              => '52cfc6409e8ecc3db661829269b0020b.png',
        'site'                => 'https://google.com',
        'capa'                => 'a9300961c8f22333fa54a3420fd5aad8.png',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '50% ou 100% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'procedimento'        => 1,
        'destaque'            => ['66'],
        'empresa'             => ['66'],
        'data_publicacao'     => dataPassadaAleatorio(),
        'estado'              => $estado,
        'tipo'                => 1,
        'status'              => 4
    ],
    [
        'cod'                 => '5d20bebb-36d5-47ce-8bc8-178309983a9a',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Parceiro Voucher Criado',
        'url'                 => 'parceiro-voucher-criado',
        'imagem'              => '2df4d9cc06a9a30a65328f47d1c77b5f.png',
        'site'                => 'https://google.com',
        'capa'                => 'bbf01d3b4583ca9d1113d236a4728232.png',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'procedimento'        => 1,
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'data_publicacao'     => dataPassadaAleatorio(),
        'estado'              => $estado,
        'tipo'                => 1,
        'status'              => 4
    ],
    [
        'id'                  => 1,
        'cod'                 => 'f10e05c0-5b02-4bff-8e22-719a8797f0d6',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Parceiro Normal',
        'url'                 => 'parceiro-normal',
        'imagem'              => 'b14eb5bfcc13d005c617112d96dd2601.png',
        'site'                => 'https://google.com',
        'capa'                => '5561e7aff08ad995e05848dea22293d3.png',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'data_publicacao'     => dataPassadaAleatorio(),
        'estado'              => $estado,
        'procedimento'        => 2,
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'tipo'                => 1,
        'status'              => 4
    ],
    [
        'id'                  => 3,
        'cod'                 => '4502e7e8-9359-470e-9588-0a1501449675',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Parceiro com limite',
        'url'                 => 'parceiro-limite',
        'imagem'              => 'd02fbee65240a30c716e22e1f42bf99f.png',
        'site'                => 'https://google.com',
        'capa'                => 'cd839e283d56d6e620488c84859ed4db.png',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'procedimento'        => 1,
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'data_publicacao'     => dataPassadaAleatorio(),
        'estado'              => $estado,
        'limite_voucher'      => 1,
        'tipo'                => 1,
        'status'              => 4
    ],
    [
        'tipo'                => 1,
        'id'                  => 4,
        'cod'                 => 'adca39ea4a6d6bcc51eba8afcdb54eaa',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Parceiro com prazo',
        'url'                 => 'parceiro-prazo',
        'imagem'              => 'c700e81160f65b498eeb4bc0190f01de.png',
        'site'                => 'https://google.com',
        'capa'                => '565ce3f0f7222d621681ae8ceeb4ffe9.png',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'desconto'            => '10% de desconto',
        'procedimento'        => 1,
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'data_publicacao'     => dataPassadaAleatorio(),
        'estado'              => [$estado[rand(0, 26)]],
        'limite_voucher'      => 10,
        'prazo_voucher'       => 5,
        'tipo'                => 1,
        'status'              => 4
    ],
    [
        'id'                  => 5,
        'cod'                 => 'f9cbb6ae-b847-43cf-b9b8-6f72b67789df',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Parceiro com prazo fixo',
        'url'                 => 'parceiro-prazo-fixo',
        'imagem'              => 'fd4855b34212cdf342ce0d0a6326e8c2.png',
        'site'                => 'https://google.com',
        'capa'                => 'cdf8d9e23e554f31612cdbbd70e7c713.jpg',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'procedimento'        => 1,
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'prazo_voucher_fixo'  => dataAdicionar(hoje(), 60, 'dias'),
        'data_publicacao'     => dataPassadaAleatorio(),
        'estado'              => [$estado[rand(0, 26)]],
        'tipo'                => 1,
        'status'              => 4
    ],
    [
        'tipo'                => 1,
        'id'                  => 4207,
        'cod'                 => 'ca0bde20602db3ec777acbbcfb5a4c61',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Blue Fit',
        'url'                 => 'bluefit',
        'imagem'              => '8c1b749f2b85c285abd1917de3c736b0.png',
        'site'                => 'https://google.com',
        'capa'                => '9badbb7d9bdbf5028821730188f6da24.png',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'procedimento'        => 3,
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'data_publicacao'     => dataPassadaAleatorio(),
        'estado'              => [$estado[rand(0, 26)]],
        'prazo_voucher_fixo'  => '2040-01-01',
        'tipo'                => 1,
        'status'              => 4
    ],
    [
        'id'                  => 15612,
        'cod'                 => 'ca0bde20602db3ec777acbbcfb5a4c62',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Madruga App de Mobilidade',
        'url'                 => 'madruga',
        'imagem'              => '28b54821a02394067f401118b104649f.png',
        'site'                => 'https://google.com',
        'capa'                => '6b6fdd202017741cf8b6a9b1d0fc3089.png',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'procedimento'        => 1,
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'prazo_voucher_fixo'  => dataAdicionar(hoje(), 60, 'dias'),
        'data_publicacao'     => dataPassadaAleatorio(),
        'estado'              => [$estado[rand(0, 26)]],
        'tipo'                => 1,
        'status'              => 4
    ],
    [
        'id'                  => 100,
        'cod'                 => '7b1476c3-2627-490c-a0cf-dff7b9196b45',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Parceiro premium 01',
        'url'                 => 'premium-01',
        'imagem'              => '297beb0e3525cd7c57f93e3bfd277c55.jpg',
        'site'                => 'https://google.com',
        'capa'                => 'c5455a016dae73b1e83b7137b2e0e376.jpg',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'procedimento'        => 1,
        'destaque'            => ['1', '1967'],
        'empresa'             => ['1', '1967'],
        'prazo_voucher'       => 5,
        'limite_voucher'      => 5,
        'data_publicacao'     => hoje(),
        'estado'              => [$estado[rand(0, 26)]],
        'tipo'                => 1,
        'status'              => 5
    ],
    [
        'id'                  => 101,
        'cod'                 => '7b1476c3-2627-490c-a0cf-dff7b9196b46',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Parceiro premium 02',
        'url'                 => 'premium-02',
        'imagem'              => 'a521fc3a1ed36aae967331b7c7f577e5.jpg',
        'site'                => 'https://google.com',
        'capa'                => 'c9b85adf5f06765c8ce4a786d4d26ca6.jpg',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'procedimento'        => 1,
        'destaque'            => ['1', '1967'],
        'empresa'             => ['1', '1967'],
        'prazo_voucher'       => 5,
        'limite_voucher'      => 5,
        'data_publicacao'     => hoje(),
        'estado'              => [$estado[rand(0, 26)]],
        'tipo'                => 1,
        'status'              => 5
    ],
    [
        'id'                  => 102,
        'cod'                 => '7b1476c3-2627-490c-a0cf-dff7b9196b47',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Parceiro premium 03',
        'url'                 => 'premium-03',
        'imagem'              => '9e2a86a6c7a7c55eb2f8e214981c8667.png',
        'site'                => 'https://google.com',
        'capa'                => 'd48d25dc727dc91240d89e4b617395a2.png',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'procedimento'        => 1,
        'destaque'            => ['1', '1967'],
        'empresa'             => ['1', '1967'],
        'prazo_voucher'       => 5,
        'limite_voucher'      => 5,
        'data_publicacao'     => hoje(),
        'estado'              => [$estado[rand(0, 26)]],
        'tipo'                => 1,
        'status'              => 5
    ],
    [
        'id'                  => 103,
        'cod'                 => '7b1476c3-2627-490c-a0cf-dff7b9196b48',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Parceiro premium 04',
        'url'                 => 'premium-04',
        'imagem'              => 'e31d56773ffd7de714f1943d4b6ca29a.jpg',
        'site'                => 'https://google.com',
        'capa'                => '5d134474b013e56d7899b80d29db6f0e.jpg',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'procedimento'        => 1,
        'destaque'            => ['1', '1967'],
        'empresa'             => ['1', '1967'],
        'prazo_voucher'       => 5,
        'limite_voucher'      => 5,
        'data_publicacao'     => hoje(),
        'estado'              => [$estado[rand(0, 26)]],
        'tipo'                => 1,
        'status'              => 5
    ],
    [
        'id'                  => 104,
        'cod'                 => '7b1476c3-2627-490c-a0cf-dff7b9196b49',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Parceiro premium 05',
        'url'                 => 'premium-05',
        'imagem'              => '495fc6081786913a45de38c9a7e8c4c2.jpg',
        'site'                => 'https://google.com',
        'capa'                => '4b3659f96f9aeb08f1a097e19da8246c.jpg',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'destaque'            => ['1', '1967'],
        'empresa'             => ['1', '1967'],
        'procedimento'        => 1,
        'prazo_voucher'       => 5,
        'limite_voucher'      => 3,
        'data_publicacao'     => hoje(),
        'estado'              => [$estado[rand(0, 26)]],
        'tipo'                => 1,
        'status'              => 5
    ],
    [
        'cod'                 => '7b1476c3-2627-490c-a0cf-dff7b9196b00',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Parceiro premium 06',
        'url'                 => 'premium-06',
        'imagem'              => '03d2b597a90afa3e3c8300f161a5f3d1.png',
        'site'                => 'https://google.com',
        'capa'                => '84169210f9e1185edf3049163d9f648d.jpg',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'destaque'            => ['1', '1967'],
        'empresa'             => ['1', '1967'],
        'procedimento'        => 1,
        'prazo_voucher'       => 5,
        'limite_voucher'      => 3,
        'tipo'                => 1,
        'status'              => 5
    ],
    [
        'cod'                 => 'f98e10ebc70e101c9d5d6fcf766d5320',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'UBER - Renner',
        'url'                 => 'uber-renner',
        'imagem'              => 'e0ec80e499c52e0b792376e90e3118c3.png',
        'site'                => 'https://google.com',
        'capa'                => '95a7206031e1465a835cb3c187d050e3.jpg',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'procedimento'        => 2,
        'tipo'                => 1,
        'status'              => 4
    ],
    [
        'cod'                 => uuid(),
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Pague Menos',
        'url'                 => 'pague-menos',
        'imagem'              => 'ec47036a3f567706e6df17a0f6d1959a.jpg',
        'site'                => 'https://google.com',
        'capa'                => '75a2313c2ff08402754cceb099705ac0.png',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'procedimento'        => 2,
        'tipo'                => 3,
        'estabelecimento'     => 1,
        'status'              => 4
    ],
    [
        'cod'                 => uuid(),
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Drograria Online',
        'url'                 => 'drograria-online',
        'imagem'              => '73a15d1ae615bf0e6371a4e42972ae4a.jpg',
        'site'                => 'https://google.com',
        'capa'                => '2b14b97d879bf40fa0a8a407dac54320.jpg',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'procedimento'        => 2,
        'tipo'                => 3,
        'estabelecimento'     => 2,
        'status'              => 4
    ],
    [
        'cod'                 => uuid(),
        'categoria_principal' => '1',
        'categoria_todas'     => '["1","2","3","4","5","6","7","8"]',
        'titulo'              => 'Drograria 2',
        'url'                 => 'drograria-2',
        'imagem'              => '4e9d9c62b31e9644666cffa1429bee19.jpg',
        'site'                => 'https://google.com',
        'capa'                => '8342037ac2e696cb551cbf83e10aa6a6.png',
        'texto'               => 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, fugiat.',
        'desconto'            => '10% de desconto',
        'desconto_texto'      => 'Texto de desconto do parceiro',
        'procedimento_texto'  => 'Texto de procedimento do parceiro',
        'voucher_texto'       => 'Texto para o voucher do parceiro',
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'procedimento'        => 2,
        'tipo'                => 3,
        'status'              => 4
    ],
    [
        'cod'                 => '259c44ede5b4302d2c65a2bc8ea0d16f',
        'categoria_principal' => '7',
        'categoria_todas'     => '["7"]',
        'titulo'              => 'Farmacia 02',
        'url'                 => 'farmacia-02',
        'imagem'              => '6abfbe8cb35fc871001df2950ed9989d.png',
        'site'                => 'https://google.com',
        'desconto'            => 'Desconto de até 6%',
        'desconto_texto'      => 'Este convênio possui condições especiais  que variam conforme o modelo de veículo desejado.
        Fique atento!
        -	A responsabilidade pela oferta, condições, formas de pagamento e serviços é da VOLVO;
        -	A disponibilidade dos veículos desta campanha é limitada, podendo variar de acordo com cada modelo, configuração, cor e ano;
        -	Os descontos também valem para seus parentes de 1º grau (pais, filhos e cônjuge).',
        'procedimento_texto' => 'Para aplicação do benefício, basta clicar em abrir site no botão ao lado e seguir as instruções:
        -    Escolha o modelo que gostaria de adquirir;
        -    Clique em "GERAR VOUCHER" no botão ao lado;
        -    Dirija-se à uma concessionária VOLVO portando o voucher e documentos e apresentar no ato da compra na concessionária.
        Não perca tempo, aproveite e boas compras!',
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'tipo'                => 3,
        'estabelecimento'     => 1,
        'procedimento'        => 2,
        'status'              => 4
    ],
    [
        'id'                  => 1000,
        'cod'                 => '7e759ba8-6043-48c4-81ff-0e1f78df17d6',
        'categoria_principal' => '7',
        'categoria_todas'     => '["7"]',
        'titulo'              => 'VOLVO - Voucher',
        'url'                 => 'volvo',
        'imagem'              => '6abfbe8cb35fc871001df2950ed9989d.png',
        'site'                => 'https://google.com',
        'desconto'            => 'Desconto de até 6%',
        'desconto_texto'      => 'Este convênio possui condições especiais  que variam conforme o modelo de veículo desejado.
        Fique atento!
        -	A responsabilidade pela oferta, condições, formas de pagamento e serviços é da VOLVO;
        -	A disponibilidade dos veículos desta campanha é limitada, podendo variar de acordo com cada modelo, configuração, cor e ano;
        -	Os descontos também valem para seus parentes de 1º grau (pais, filhos e cônjuge).',
        'procedimento_texto' => 'Para aplicação do benefício, basta clicar em abrir site no botão ao lado e seguir as instruções:
        -    Escolha o modelo que gostaria de adquirir;
        -    Clique em "GERAR VOUCHER" no botão ao lado;
        -    Dirija-se à uma concessionária VOLVO portando o voucher e documentos e apresentar no ato da compra na concessionária.
        Não perca tempo, aproveite e boas compras!',
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'tipo'                => 2,
        'estabelecimento'     => 1,
        'procedimento'        => 1,
        'status'              => 4
    ],
    [
        'id'                  => 1001,
        'cod'                 => '9ee16428-8456-46dd-bfff-92f1a8fc685f',
        'categoria_principal' => '7',
        'categoria_todas'     => '["7"]',
        'titulo'              => 'Honda - Declaracao',
        'url'                 => 'honda',
        'imagem'              => '6abfbe8cb35fc871001df2950ed9989d.png',
        'site'                => 'https://google.com',
        'desconto'            => 'Desconto de até 6%',
        'desconto_texto'      => 'Este convênio possui condições especiais  que variam conforme o modelo de veículo desejado.
        Fique atento!
        -	A responsabilidade pela oferta, condições, formas de pagamento e serviços é da VOLVO;
        -	A disponibilidade dos veículos desta campanha é limitada, podendo variar de acordo com cada modelo, configuração, cor e ano;
        -	Os descontos também valem para seus parentes de 1º grau (pais, filhos e cônjuge).',
        'procedimento_texto' => 'Para aplicação do benefício, basta clicar em abrir site no botão ao lado e seguir as instruções:
        -    Escolha o modelo que gostaria de adquirir;
        -    Clique em "GERAR VOUCHER" no botão ao lado;
        -    Dirija-se à uma concessionária VOLVO portando o voucher e documentos e apresentar no ato da compra na concessionária.
        Não perca tempo, aproveite e boas compras!',
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'tipo'                => 2,
        'estabelecimento'     => 1,
        'procedimento'        => 3,
        'status'              => 4
    ],
    [
        'id'                  => 1002,
        'cod'                 => '9ee16428-8456-46dd-bfff-92f1a8fc685d',
        'categoria_principal' => '7',
        'categoria_todas'     => '["7"]',
        'titulo'              => 'Chevrolet - Cheque Bonus',
        'url'                 => 'chevrolet',
        'imagem'              => '6abfbe8cb35fc871001df2950ed9989d.png',
        'site'                => 'https://google.com',
        'desconto'            => 'Desconto de até 6%',
        'desconto_texto'      => 'Este convênio possui condições especiais  que variam conforme o modelo de veículo desejado.
        Fique atento!
        -	A responsabilidade pela oferta, condições, formas de pagamento e serviços é da VOLVO;
        -	A disponibilidade dos veículos desta campanha é limitada, podendo variar de acordo com cada modelo, configuração, cor e ano;
        -	Os descontos também valem para seus parentes de 1º grau (pais, filhos e cônjuge).',
        'procedimento_texto' => 'Para aplicação do benefício, basta clicar em abrir site no botão ao lado e seguir as instruções:
        -    Escolha o modelo que gostaria de adquirir;
        -    Clique em "GERAR VOUCHER" no botão ao lado;
        -    Dirija-se à uma concessionária VOLVO portando o voucher e documentos e apresentar no ato da compra na concessionária.
        Não perca tempo, aproveite e boas compras!',
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'tipo'                => 2,
        'estabelecimento'     => 1,
        'procedimento'        => 4,
        'status'              => 4
    ],
    [
        'cod'                 => 'dadfe939-4787-4f9e-96c6-79659605d3a0',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1"]',
        'titulo'              => 'Parceiro Mapa 01',
        'url'                 => 'parceiro-mapa-01',
        'imagem'              => '6abfbe8cb35fc871001df2950ed9989d.png',
        'site'                => 'https://google.com',
        'desconto'            => 'Desconto de até 6%',
        'desconto_texto'      => 'Este convênio possui condições especiais  que variam conforme o modelo de veículo desejado.',
        'procedimento_texto'  => 'Para aplicação do benefício, basta clicar em abrir site no botão ao lado e seguir as instruções.',
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'tipo'                => 1,
        'estabelecimento'     => 1,
        'procedimento'        => 1,
        'status'              => 4
    ],
    [
        'cod'                 => '4b08f0dd-ef65-4269-bb57-007346f23890',
        'categoria_principal' => '1',
        'categoria_todas'     => '["1"]',
        'titulo'              => 'Parceiro Mapa 02',
        'url'                 => 'parceiro-mapa-02',
        'imagem'              => 'c700e81160f65b498eeb4bc0190f01de.png',
        'site'                => 'https://google.com',
        'desconto'            => 'Desconto de até 6%',
        'desconto_texto'      => 'Este convênio possui condições especiais  que variam conforme o modelo de veículo desejado.',
        'procedimento_texto'  => 'Para aplicação do benefício, basta clicar em abrir site no botão ao lado e seguir as instruções.',
        'destaque'            => ['1', '2', '66'],
        'empresa'             => ['1', '2', '66'],
        'tipo'                => 1,
        'estabelecimento'     => 1,
        'procedimento'        => 1,
        'status'              => 4
    ],
];
