<?php 

define("TABELA_ADMIN_EMPRESA", "admin_empresa");
define("TABELA_AUTH_APP", "auth_app");
define("TABELA_AUTH_BLACK_LIST", "auth_black_list");
define("TABELA_AUTH_LOG", "auth_log");
define("TABELA_AUTH_TOKEN", "auth_token");
define("TABELA_AUTH_USUARIO", "auth_usuario");
define("TABELA_CAMPANHA_SORTEIO", "campanha_sorteio");
define("TABELA_CONSTRUTOR_NOVO", "construtor_novo");
define("TABELA_EMPRESA_NOVO", "empresa_novo");
define("TABELA_LOG_ERRO", "log_erro");
define("TABELA_PAINEL_AGENDA", "painel_agenda");
define("TABELA_PAINEL_CONFIG", "painel_config");
define("TABELA_PAINEL_HISTORICO", "painel_historico");
define("TABELA_PAINEL_LOG_DOWNLOAD", "painel_log_download");
define("TABELA_PAINEL_MENU", "painel_menu");
define("TABELA_PAINEL_NOTIFICACAO", "painel_notificacao");
define("TABELA_PARCEIRO_ACESSADO", "parceiro_acessado");
define("TABELA_PARCEIRO_NOVO", "parceiro_novo");
define("TABELA_SOLICITACAO_VOUCHER", "solicitacao_voucher");
define("TABELA_UPLOAD_ARQUIVO", "upload_arquivo");
define("TABELA_UPLOAD_GRUPO", "upload_grupo");
define("TABELA_USUARIO_EQUIPE", "usuario_equipe");
define("TABELA_USUARIO_INDICACAO", "usuario_indicacao");
define("TABELA_USUARIO_LEAD", "usuario_lead");
define("TABELA_USUARIO_NOVO", "usuario_novo");
define("TABELA_USUARIO_PAGAMENTO", "usuario_pagamento");
define("TABELA_USUARIO_RELATORIO", "usuario_relatorio");