<?php

return (new \DataBase\DataBase())
    ->id()
    ->char('cod')->tamanho(36)
    ->nome('razao_social')
    ->nome('nome_fantasia')
    ->cnpj('cnpj')->unico()
    ->nome('responsavel_nome')
    ->cpf('responsavel_cpf')->unico()
    ->email('responsavel_email')->null()
    ->telefone('responsavel_telefone')->null()
    ->text('item_contratado')
    ->text('tag')->null()
    ->int('endereco_cep')->tamanho(8)->null()
    ->char('endereco_estado')->tamanho(2)
    ->varchar('endereco_cidade')->tamanho(50)
    ->varchar('endereco_logradouro')->tamanho(100)->null()
    ->int('endereco_numero')->tamanho(7)->null()
    ->varchar('endereco_complemento')->tamanho(100)->null()
    ->varchar('endereco_referenncia')->tamanho(100)->null()
    ->varchar('endereco_bairro')->tamanho(50)->null()
    ->imagem('imagem_arquivo')->null()
    ->dataCriacao()
    ->dataAtualizacao()
    ->status();
