<?php

return [
    [
        'id' => 1,
        'cod' => '14afa776394ada4be23be6acf7e3259e',
        'id_usuario_equipe' => 1,
        'titulo' => 'Markt Club',
        'razao_social' => 'Markt Club',
        'nome_fantasia' => 'Markt Club',
        'cnpj' => 14150830000100,
        'responsavel_nome' => 'André Rodrigues',
        'responsavel_cpf' => 1495180131,
        'responsavel_email' => 'andre@marktclub.com.br',
        'responsavel_telefone' => 61981777773,
        'slug' => 'marktclub',
        'status' => 1
    ],
    [
        'id' => 2,
        'cod' => '0ffc5c56b99f81ca0edea8bdf524b688',
        'id_usuario_equipe' => 1,
        'titulo' => 'Anafe Card',
        'razao_social' => 'Anafe Card',
        'nome_fantasia' => 'Anafe Card',
        'cnpj' => 24323554000198,
        'responsavel_nome' => nomeCompletoAleatorio(),
        'responsavel_cpf' => cpfAleatorio(),
        'responsavel_email' => emailAleatorio(),
        'responsavel_telefone' => telefoneCelularAleatorio(),
        'slug' => 'anafe',
        'status' => 1
    ],
    [
        'id' => 198,
        'cod' => '42727943964c0800356dde841ff62800',
        'id_usuario_equipe' => 1,
        'titulo' => 'CVS Mais',
        'razao_social' => 'CVS Mais',
        'nome_fantasia' => 'CVS Mais',
        'cnpj' => 61651675000195,
        'responsavel_nome' => nomeCompletoAleatorio(),
        'responsavel_cpf' => cpfAleatorio(),
        'responsavel_email' => emailAleatorio(),
        'responsavel_telefone' => telefoneCelularAleatorio(),
        'slug' => 'cvsmais',
        'status' => 1
    ],
    [
        'id' => 223,
        'cod' => '62c6e14371c10bf6ffb20325af002e7e',
        'id_usuario_equipe' => 1,
        'titulo' => 'Banco Digio',
        'razao_social' => 'Banco Digio',
        'nome_fantasia' => 'Banco Digio',
        'cnpj' => 27098060000145,
        'responsavel_nome' => nomeCompletoAleatorio(),
        'responsavel_cpf' => cpfAleatorio(),
        'responsavel_email' => emailAleatorio(),
        'responsavel_telefone' => telefoneCelularAleatorio(),
        'slug' => 'bancodigio',
        'status' => 1
    ],
    [
        'cod' => '14afa776394ada4be23be6acf7e3259f',
        'id_usuario_equipe' => 1,
        'id_admin_empresa' => 1,
        'titulo' => 'Sub Empresa Markt Club',
        'razao_social' => 'Sub Empresa Markt Club',
        'nome_fantasia' => 'Sub Empresa Markt Club',
        'cnpj' => 42353214000191,
        'responsavel_nome' => 'André Rodrigues',
        'responsavel_cpf' => 1495180131,
        'responsavel_email' => 'andre2@marktclub.com.br',
        'responsavel_telefone' => 61981777772,
        'slug' => 'sub-marktclub',
        'status' => 1
    ],
    [
        'cod' => uuid(),
        'id_usuario_equipe' => 1,
        'titulo' => 'Prospecção Nome 01',
        'razao_social' => 'Prospecção Nome 01',
        'nome_fantasia' => 'Prospecção Nome 01',
        'cnpj' => cnpjAleatorio(),
        'responsavel_nome' => nomeCompletoAleatorio(),
        'responsavel_cpf' => cpfAleatorio(),
        'responsavel_email' => emailAleatorio(),
        'responsavel_telefone' => telefoneCelularAleatorio(),
        'prospeccao_status' => 1,
        'slug' => 'nome-01',
        'status' => 3
    ],
    [
        'cod' => uuid(),
        'id_usuario_equipe' => 1,
        'titulo' => 'Prospecção Nome 02',
        'razao_social' => 'Prospecção Nome 02',
        'nome_fantasia' => 'Prospecção Nome 02',
        'cnpj' => cnpjAleatorio(),
        'responsavel_nome' => nomeCompletoAleatorio(),
        'responsavel_cpf' => cpfAleatorio(),
        'responsavel_email' => emailAleatorio(),
        'responsavel_telefone' => telefoneCelularAleatorio(),
        'prospeccao_status' => 1,
        'slug' => 'nome-02',
        'status' => 3
    ],
    [
        'cod' => uuid(),
        'id_usuario_equipe' => 1,
        'titulo' => 'Prospecção Nome 03',
        'razao_social' => 'Prospecção Nome 03',
        'nome_fantasia' => 'Prospecção Nome 03',
        'cnpj' => cnpjAleatorio(),
        'responsavel_nome' => nomeCompletoAleatorio(),
        'responsavel_cpf' => cpfAleatorio(),
        'responsavel_email' => emailAleatorio(),
        'responsavel_telefone' => telefoneCelularAleatorio(),
        'prospeccao_status' => 1,
        'slug' => 'nome-03',
        'status' => 3
    ],
];
