<?php

return [
    [
        'id'                      => 1,
        'cod'                     => '14afa776394ada4be23be6acf7e3259e',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Markt Club',
        'razao_social'            => 'Markt Club',
        'nome_fantasia'           => 'Markt Club',
        'cnpj'                    => 14150830000100,
        'responsavel_nome'        => 'André Rodrigues',
        'responsavel_cpf'         => 1495180131,
        'responsavel_email'       => 'andre@marktclub.com.br',
        'responsavel_telefone'    => 61981777773,
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'slug'                    => 'marktclub',
        'status'                  => 1
    ],
    [
        'id'                      => 2,
        'cod'                     => '0ffc5c56b99f81ca0edea8bdf524b688',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Anafe Card',
        'razao_social'            => 'Anafe Card',
        'nome_fantasia'           => 'Anafe Card',
        'cnpj'                    => 24323554000198,
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'slug'                    => 'anafe',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
    [
        'id'                      => 3,
        'cod'                     => '8c85bc5bfd7093b175a7d44fdeb5050c',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'APCF Card',
        'razao_social'            => 'APCF Card',
        'nome_fantasia'           => 'APCF Card',
        'cnpj'                    => 33521352000141,
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'slug'                    => 'apcf',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
    [
        'id'                      => 19,
        'cod'                     => '4cceef2a4ee3d677dd15955daace4bba',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Unareg',
        'razao_social'            => 'Unareg',
        'nome_fantasia'           => 'Unareg',
        'cnpj'                    => '07597210000158',
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'slug'                    => 'unareg',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
    [
        'id'                      => 153,
        'cod'                     => '369fc307129e405b3f2f00620c7b012d',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Fenae',
        'razao_social'            => 'Fenae',
        'nome_fantasia'           => 'Fenae',
        'cnpj'                    => 3636693000100,
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'slug'                    => 'fenae',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
    [
        'id'                      => 198,
        'cod'                     => '42727943964c0800356dde841ff62800',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'CVS Mais',
        'razao_social'            => 'CVS Mais',
        'nome_fantasia'           => 'CVS Mais',
        'cnpj'                    => 61651675000195,
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'slug'                    => 'cvsmais',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
    [
        'id'                      => 223,
        'cod'                     => '62c6e14371c10bf6ffb20325af002e7e',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Banco Digio',
        'razao_social'            => 'Banco Digio',
        'nome_fantasia'           => 'Banco Digio',
        'cnpj'                    => 27098060000145,
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'slug'                    => 'bancodigio',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
    [
        'id'                      => 1967,
        'cod'                     => '9954c5edcc9a7b72fed65715f326df81',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Grupo diário',
        'razao_social'            => 'Grupo diário',
        'nome_fantasia'           => 'Grupo diário',
        'cnpj'                    => 26748774000199,
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'slug'                    => 'grupodiario',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
    [
        'cod'                     => '14afa776394ada4be23be6acf7e3259f',
        'id_usuario_equipe'       => 1,
        'id_admin_empresa'        => 1,
        'titulo'                  => 'Sub Empresa Markt Club',
        'razao_social'            => 'Sub Empresa Markt Club',
        'nome_fantasia'           => 'Sub Empresa Markt Club',
        'cnpj'                    => 42353214000191,
        'responsavel_nome'        => 'André Rodrigues',
        'responsavel_cpf'         => 1495180131,
        'responsavel_email'       => 'andre2@marktclub.com.br',
        'responsavel_telefone'    => 61981777772,
        'slug'                    => 'sub-marktclub',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
    [
        'id'                      => 7,
        'cod'                     => uuid(),
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Prospecção Nome 01',
        'razao_social'            => 'Prospecção Nome 01',
        'nome_fantasia'           => 'Prospecção Nome 01',
        'cnpj'                    => cnpjAleatorio(),
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'prospeccao_status'       => 1,
        'slug'                    => 'nome-01',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'finalidade_empresa'      => 1,
        'finalidade_secundaria'   => 1,
        'status'                  => 3
    ],
    [
        'id'                      => 5,
        'cod'                     => uuid(),
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Prospecção Nome 02',
        'razao_social'            => 'Prospecção Nome 02',
        'nome_fantasia'           => 'Prospecção Nome 02',
        'cnpj'                    => cnpjAleatorio(),
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'prospeccao_status'       => 1,
        'slug'                    => 'nome-02',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'finalidade_empresa'      => 1,
        'finalidade_secundaria'   => 1,
        'status'                  => 3
    ],
    [
        'id'                      => 6,
        'cod'                     => uuid(),
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Prospecção Nome 03',
        'razao_social'            => 'Prospecção Nome 03',
        'nome_fantasia'           => 'Prospecção Nome 03',
        'cnpj'                    => cnpjAleatorio(),
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'prospeccao_status'       => 1,
        'slug'                    => 'nome-03',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'finalidade_empresa'      => 1,
        'finalidade_secundaria'   => 1,
        'status'                  => 3
    ],
    [
        'id'                      => 229,
        'cod'                     => 'ea964013e0feec5b5f52bc8a94fe7574',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Cemecard',
        'razao_social'            => 'Cemecard',
        'nome_fantasia'           => 'Cemecard',
        'cnpj'                    => 48722524000112,
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'slug'                    => 'cemecard',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
    [
        'id'                      => 82,
        'cod'                     => '61df17919405cf68f723510ec3af4acd',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Sinpol-DF',
        'razao_social'            => 'Sinpol-DF',
        'nome_fantasia'           => 'Sinpol-DF',
        'cnpj'                    => 53545733000178,
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'slug'                    => 'sinpol-df',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
    [
        'id'                      => 4,
        'cod'                     => '34be95dcb312e99aa17c3d0deab5556b',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'Asagu Card',
        'razao_social'            => 'Asagu Card',
        'nome_fantasia'           => 'Asagu Card',
        'cnpj'                    => 30133813000110,
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'slug'                    => 'asagu',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
    [
        'id'                      => 2009,
        'cod'                     => '8aa3438a-3e38-4067-8a9f-9dba6888f710',
        'id_usuario_equipe'       => 1,
        'titulo'                  => 'GEAP',
        'razao_social'            => 'GEAP',
        'nome_fantasia'           => 'GEAP',
        'cnpj'                    => 3658432000182,
        'responsavel_nome'        => nomeCompletoAleatorio(),
        'responsavel_cpf'         => cpfAleatorio(),
        'responsavel_email'       => emailAleatorio(),
        'responsavel_telefone'    => telefoneCelularAleatorio(),
        'slug'                    => 'geap',
        'tipo_pagamento'          => 1,
        'contrato_valor'          => 1.2,
        'contrato_dia_fechamento' => 1,
        'contrato_dia_pagamento'  => 10,
        'cobrar_aposentado'       => 1,
        'status'                  => 1
    ],
];
