<?php

use DataBase\DataBase;

return (new DataBase())
    ->id()
    ->uuid()
    ->int('id_admin_empresa')->tamanho(9)
    ->int('id_usuario_cliente')->tamanho(9)->relacionado(TABELA_USUARIO_CLIENTE, 'id')
    ->char('id_saude_simulacao')->tamanho(36)->relacionado(TABELA_SAUDE_SIMULACAO, 'id')
    ->cpf()
    ->varchar('documento_rg')->tamanho(30)->null()
    ->varchar('orgao_expedidor')->tamanho(30)->null()
    ->nome('nome')
    ->date('data_nascimento')
    ->varchar('estado_civil')->tamanho(20)->null()
    ->varchar('naturalidade')->tamanho(20)->null()
    ->tinyint('genero')->tamanho(1)
    ->varchar('peso')->tamanho(5)
    ->varchar('altura')->tamanho(5)
    ->varchar('nome_mae')->tamanho(25)->null()
    ->cpf('responsavel_cpf')->null()
    ->varchar('responsavel_rg')->tamanho(30)->null()
    ->nome('responsavel_nome')->null()
    ->varchar('responsavel_orgao_expedidor')->null()->tamanho(30)
    ->email('email_pessoal')
    ->telefone('telefone_celular')
    ->telefone('telefone_residencial')->null()
    ->telefone('telefone_comercial')
    ->varchar('telefone_comercial_ramal')->tamanho(10)->null()
    ->varchar('endereco_logradouro')->tamanho(256)
    ->char('endereco_cep')->tamanho(8)
    ->varchar('endereco_estado')->tamanho(40)
    ->varchar('endereco_cidade')->tamanho(100)
    ->varchar('endereco_bairro')->tamanho(100)
    ->int('endereco_numero')->tamanho(5)
    ->varchar('endereco_complemento')->tamanho(256)->null()
    ->dataCriacao()
    ->dataAtualizacao()
    ->status();
