<?php

use DataBase\DataBase;

return (new DataBase())
    ->id()
    ->uuid()
    ->int('id_admin_empresa')->tamanho(9)
    ->int('id_usuario')->tamanho(9)
    ->char('id_simulacao')->tamanho(36)
    ->cpf()
    ->varchar('documento_rg')->tamanho(30)->null()
    ->varchar('orgao_expedidor')->tamanho(30)->null()
    ->nome('nome')
    ->date('data_nascimento')
    ->varchar('estado_civil')->tamanho(20)->null()
    ->varchar('naturalidade')->tamanho(20)->null()
    ->tinyint('sexo')->tamanho(1)
    ->varchar('peso')->tamanho(5)
    ->varchar('altura')->tamanho(5)
    ->varchar('filiacao')->tamanho(25)->null()
    ->cpf('cpf_responsavel')
    ->varchar('rg_responsavel')->tamanho(30)->null()
    ->nome('nome_responsavel')
    ->email('email')
    ->telefone('telefone_celular')
    ->telefone('telefone_residencial')
    ->telefone('telefone_comercial')
    ->varchar('ramal')->tamanho(10)->null()
    ->varchar('endereco')->tamanho(256)
    ->char('cep')->tamanho(8)
    ->varchar('estado')->tamanho(40)
    ->varchar('cidade')->tamanho(100)
    ->varchar('bairro')->tamanho(100)
    ->int('numero')->tamanho(5)
    ->varchar('complemento')->tamanho(256)
    ->status()
    ->dataCriacao()
    ->dataAtualizacao();
