<?php

return (new \DataBase\DataBase())
    ->id()
    ->uuid()
    ->int('id_admin_empresa')->tamanho(9)
    ->varchar('nome')->tamanho(80)
    ->text('descricao')
    ->imagem('imagem_app')->null()
    ->text('chave_privada')->unico()
    ->text('chave_publica')->unico()
    ->char('secret_id')->tamanho(80)->unico()->unico()
    ->char('client_id')->tamanho(100)->unico()->unico()
    ->char('audience')->tamanho(60)
    ->text('chave_privada_fake')->unico()
    ->text('chave_publica_fake')->unico()
    ->char('secret_id_fake')->tamanho(80)->unico()->unico()
    ->char('client_id_fake')->tamanho(100)->unico()->unico()
    ->int('authorization_code')->tamanho(1)->null()
    ->int('client_credentials')->tamanho(1)->null()
    ->int('refresh_token')->tamanho(1)->null()
    ->json('redirect_uri')->null()
    ->json('scope_permitido')
    ->json('campo_permitido')->null()
    ->int('tempo_vida')->tamanho(9)
    ->dataCriacao()
    ->dataAtualizacao()
    ->status();
