<?php

return (new \DataBase\DataBase())
    ->id()
    ->uuid()
    ->char('id_usuario')->tamanho(36)
    ->int('id_api_app')->tamanho(9)->relacionado(TABELA_AUTH_APP, 'id')
    ->text('redirect_uri')->null()
    ->text('scope_permitido')
    ->varchar('state_cliente')->tamanho(36)
    ->char('authorization_code')->tamanho(36)->unico()
    ->char('access_token')->tamanho(36)->null()->unico()
    ->char('refresh_token')->tamanho(36)->null()->unico()
    ->varchar('grant_type')->tamanho(20)
    ->varchar('ip')->tamanho(40)->null()
    ->varchar('sistema_operacional')->tamanho(40)->null()
    ->varchar('navegador')->tamanho(40)->null()
    ->char('hash')->tamanho(36)
    ->dataCriacao()
    ->dataAtualizacao()
    ->datetime('data_ativacao')->null()
    ->datetime('data_revogacao')->null()
    ->datetime('data_vencimento')->null()
    ->status();
