<?php

return [
    [
        'cod'                  => uuid(),
        'empresa'              => 1,
        'usuario'              => 1,
        'vinculo'              => '7b1476c3-2627-490c-a0cf-dff7b9196b01',
        'titulo'               => 'Voucher premium 01',
        'tipo'                 => 1,
        'tipo_usuario'         => 1,
        'valor'                => number_format(numeroAleatorio(), 2, thousands_separator: ''),
        'codigo'               => strCodigo(8),
        'data_vencimento'      => dataAdicionar(agora(), 2, 'dia'),
        'data_validacao'       => null,
        'status'               => 2
    ],
    [
        'cod'                  => uuid(),
        'empresa'              => 1,
        'usuario'              => 1,
        'vinculo'              => '7b1476c3-2627-490c-a0cf-dff7b9196b01',
        'titulo'               => 'Voucher premium 01',
        'tipo'                 => 1,
        'tipo_usuario'         => 1,
        'valor'                => number_format(numeroAleatorio(), 2, thousands_separator: ''),
        'codigo'               => strCodigo(8),
        'data_vencimento'      => dataAdicionar(agora(), 2, 'dia'),
        'data_validacao'       => null,
        'status'               => 2
    ],
    [
        'cod'                  => uuid(),
        'empresa'              => 1,
        'usuario'              => 1,
        'vinculo'              => '7b1476c3-2627-490c-a0cf-dff7b9196b02',
        'titulo'               => 'Voucher premium 02',
        'tipo'                 => 1,
        'tipo_usuario'         => 1,
        'valor'                => number_format(numeroAleatorio(), 2, thousands_separator: ''),
        'codigo'               => strCodigo(8),
        'data_vencimento'      => dataAdicionar(agora(), 2, 'dia'),
        'data_validacao'       => null,
        'status'               => 2
    ],
    [
        'cod'                  => uuid(),
        'empresa'              => 1,
        'usuario'              => 1,
        'vinculo'              => '7b1476c3-2627-490c-a0cf-dff7b9196b04',
        'titulo'               => 'Voucher premium 04',
        'tipo'                 => 1,
        'tipo_usuario'         => 1,
        'valor'                => number_format(numeroAleatorio(), 2, thousands_separator: ''),
        'codigo'               => strCodigo(8),
        'data_vencimento'      => dataAdicionar(agora(), 2, 'dia'),
        'data_validacao'       => null,
        'status'               => 2
    ],
    [
        'cod'                  => uuid(),
        'empresa'              => 1,
        'usuario'              => 1,
        'vinculo'              => '7b1476c3-2627-490c-a0cf-dff7b9196b04',
        'titulo'               => 'Voucher premium 04',
        'tipo'                 => 1,
        'tipo_usuario'         => 1,
        'valor'                => number_format(numeroAleatorio(), 2, thousands_separator: ''),
        'codigo'               => strCodigo(8),
        'data_vencimento'      => dataAdicionar(agora(), 2, 'dia'),
        'data_validacao'       => null,
        'status'               => 1
    ],
    [
        'cod'                  => uuid(),
        'empresa'              => 1,
        'usuario'              => 1,
        'vinculo'              => '7b1476c3-2627-490c-a0cf-dff7b9196b06',
        'titulo'               => 'Voucher premium 06',
        'tipo'                 => 1,
        'tipo_usuario'         => 1,
        'valor'                => number_format(numeroAleatorio(), 2, thousands_separator: ''),
        'codigo'               => strCodigo(8),
        'data_vencimento'      => dataAdicionar(agora(), 2, 'dia'),
        'data_validacao'       => null,
        'status'               => 2
    ],
];
