<?php

return [
    [
        'cod'                  => uuid(),
        'empresa'              => 1,
        'usuario'              => 1,
        'vinculo'              => '890713a200a9e45aa85e2ae67aa41e74',
        'titulo'               => 'Titulo',
        'tipo'                 => 1,
        'tipo_usuario'         => 1,
        'valor'                => number_format(numeroAleatorio(), 2, thousands_separator: ''),
        'codigo'               => strtoupper(uniqid()),
        'quantidade_voucher'   => 9,
        'documento_dependente' => cpfAleatorio(),
        'data_vencimento'      => dataAdicionar(agora(), 30, 'dia'),
        'data_validacao'       => null,
        'status'               => 2
    ],
    [
        'cod'             => uuid(),
        'tipo'            => 1,
        'tipo_usuario'    => 1,
        'vinculo'         => '5d20bebb-36d5-47ce-8bc8-178309983a9a',
        'usuario'         => 1,
        'empresa'         => 1,
        'codigo'          => 'abcde12345',
        'data_criacao'    => dataRemover(agora(), 10, 'minutos', 'Y-m-d H:i:s'),
        'data_vencimento' => dataAdicionar(agora(), 10, 'dia', 'Y-m-d'),
        'status'          => 3,
    ],
    [
        'cod'             => uuid(),
        'tipo'            => 1,
        'tipo_usuario'    => 1,
        'vinculo'         => '4502e7e8-9359-470e-9588-0a1501449675',
        'usuario'         => 1,
        'empresa'         => 1,
        'codigo'          => rand(10000000, 99999999),
        'data_criacao'    => dataRemover(agora(), 10, 'dia', 'Y-m-d H:i:s'),
        'data_vencimento' => dataRemover(agora(), 5, 'dia', 'Y-m-d'),
        'status'          => 3,
    ],
    [
        'cod'             => uuid(),
        'tipo'            => 1,
        'tipo_usuario'    => 1,
        'vinculo'         => 'b8bec1588ffa1c73f7d7d695cfae1150',
        'usuario'         => 1,
        'empresa'         => 1,
        'data_criacao'    => dataRemover(agora(), 1, 'dia', 'Y-m-d H:i:s'),
        'data_vencimento' => dataAdicionar(hoje(), 4, 'dias'),
        'codigo'          => '123123123',
        'status'          => 1,
    ],
    [
        'cod'             => uuid(),
        'tipo'            => 1,
        'tipo_usuario'    => 1,
        'vinculo'         => 'adca39ea4a6d6bcc51eba8afcdb54eaa',
        'usuario'         => 3,
        'empresa'         => 1,
        'codigo'          => rand(10000000, 99999999),
        'data_criacao'    => dataRemover(agora(), 10, 'dia', 'Y-m-d H:i:s'),
        'data_vencimento' => dataRemover(agora(), 5, 'dia', 'Y-m-d'),
        'status'          => 3,
    ],
    [
        'cod'             => uuid(),
        'tipo'            => 1,
        'tipo_usuario'    => 1,
        'vinculo'         => '7b1476c3-2627-490c-a0cf-dff7b9196b00',
        'usuario'         => 100,
        'empresa'         => 1967,
        'codigo'          => rand(10000000, 99999999),
        'data_criacao'    => dataPrimeiroDiaMes(hoje() . ' 00:00:00'),
        'data_vencimento' => dataPrimeiroDiaMes(hoje()),
        'status'          => 2,
    ]
];
