<?php

return (new \DataBase\DataBase())
    ->id()
    ->int('usuario')->tamanho(9)
    ->int('empresa')->tamanho(9)
    ->int('vinculo')->tamanho(9)->null()
    ->int('usuario_tipo')->tamanho(9)
    ->char('hash')
    ->varchar('ip')->tamanho(15)
    ->text('agent')
    ->varchar('dispositivo')->null()
    ->varchar('os')->null()
    ->varchar('browser')->null()
    ->varchar('versao')->null()
    ->int('mobile')->null()
    ->int('tablet')->null()
    ->varchar('pais')->tamanho(2)->null()
    ->varchar('uf')->tamanho(2)->null()
    ->varchar('cidade')->tamanho(2)->null()
    ->varchar('latitude')->tamanho(2)->null()
    ->varchar('longitude')->tamanho(2)->null()
    ->text('url')
    ->dataCriacao()
    ->status();
