<?php

return (new \DataBase\DataBase())
    ->id()
    ->uuid()
    ->char('id_vinculo')->tamanho(36)
    ->varchar('local_principal')->tamanho(100)
    ->varchar('local_secundario')->tamanho(100)
    ->nome('titulo')->null()
    ->varchar('cep')->tamanho(20)->null()
    ->varchar('logradouro')->tamanho(200)->null()
    ->varchar('complemento')->tamanho(100)->null()
    ->varchar('referencia')->tamanho(100)->null()
    ->varchar('numero')->tamanho(20)->null()
    ->varchar('bairro')->tamanho(50)->null()
    ->varchar('cidade')->tamanho(50)->null()
    ->varchar('estado')->tamanho(50)->null()
    ->char('pais')->tamanho(2)->null()
    ->varchar('latitude')->tamanho(40)->null()
    ->varchar('longitude')->tamanho(40)->null()
    ->dataCriacao()
    ->dataAtualizacao()
    ->int('principal')->tamanho(1)->null();
