<?php

return (new \DataBase\DataBase())
    ->id()
    ->uuid()
    ->char('cod')->tamanho(36)->replace('id_vinculo')
    ->varchar('tabela')->tamanho(100)
    ->int('local')
    ->nome('nome')->null()->replace('titulo')
    ->telefone('telefone')->null()
    ->cep('cep')->null()
    ->varchar('logradouro')->tamanho(200)->null()
    ->varchar('complemento')->tamanho(100)->null()
    ->varchar('referencia')->tamanho(100)->null()
    ->varchar('numero')->tamanho(20)->null()
    ->varchar('bairro')->tamanho(50)->null()
    ->varchar('cidade')->tamanho(50)->null()
    ->char('estado')->tamanho(2)->null()
    ->char('pais')->tamanho(2)->null()
    ->varchar('latitude')->tamanho(40)->null()
    ->varchar('longitude')->tamanho(40)->null()
    ->dataCriacao()
    ->dataAtualizacao()
    ->int('principal')->tamanho(1)->null();
